/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Asya Backend API
 * API documentation for Asya Backend application
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  DelegateAttrConfigCreateRequest,
  DelegateAttrConfigUpdateRequest,
  DelegateAttrManageQueryRequest,
  DelegateAttrRecordUpsertRequest,
  ListMyRecordsParams,
  QueryForManagementParams,
} from "../asyaBackendAPI.schemas";

import { customInstance } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const appendQueryParam = (
  normalizedParams: URLSearchParams,
  key: string,
  value: unknown,
) => {
  if (value === undefined || value === null) return;
  if (typeof value === "string" && value.trim() === "") return;
  normalizedParams.append(key, String(value));
};

const buildQueryString = (params?: Record<string, unknown>) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value === undefined || value === null) return;

    if (key === "pageable" && typeof value === "object" && !Array.isArray(value)) {
      const pageable = value as {
        page?: number;
        size?: number;
        sort?: string[];
      };
      appendQueryParam(normalizedParams, "page", pageable.page);
      appendQueryParam(normalizedParams, "size", pageable.size);
      if (Array.isArray(pageable.sort)) {
        pageable.sort.forEach((sort) =>
          appendQueryParam(normalizedParams, "sort", sort),
        );
      }
      return;
    }

    if (Array.isArray(value)) {
      value.forEach((item) => appendQueryParam(normalizedParams, key, item));
      return;
    }

    appendQueryParam(normalizedParams, key, value);
  });

  return normalizedParams.toString();
};

/**
 * 仅 SYS_ADMIN / DH / DM 可访问
 * @summary 覆盖更新代表属性记录
 */
export type updateRecordResponse200 = {
  data: Blob;
  status: 200;
};

export type updateRecordResponseSuccess = updateRecordResponse200 & {
  headers: Headers;
};
export type updateRecordResponse = updateRecordResponseSuccess;

export const getUpdateRecordUrl = (delegateId: string, recordId: string) => {
  return `/api/delegate-attrs/delegates/${delegateId}/records/${recordId}`;
};

export const updateRecord = async (
  delegateId: string,
  recordId: string,
  delegateAttrRecordUpsertRequest: DelegateAttrRecordUpsertRequest,
  options?: RequestInit,
): Promise<updateRecordResponse> => {
  return customInstance<updateRecordResponse>(
    getUpdateRecordUrl(delegateId, recordId),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(delegateAttrRecordUpsertRequest),
    },
  );
};

export const getUpdateRecordMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateRecord>>,
    TError,
    {
      delegateId: string;
      recordId: string;
      data: DelegateAttrRecordUpsertRequest;
    },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateRecord>>,
  TError,
  {
    delegateId: string;
    recordId: string;
    data: DelegateAttrRecordUpsertRequest;
  },
  TContext
> => {
  const mutationKey = ["updateRecord"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateRecord>>,
    {
      delegateId: string;
      recordId: string;
      data: DelegateAttrRecordUpsertRequest;
    }
  > = (props) => {
    const { delegateId, recordId, data } = props ?? {};

    return updateRecord(delegateId, recordId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateRecordMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateRecord>>
>;
export type UpdateRecordMutationBody = DelegateAttrRecordUpsertRequest;
export type UpdateRecordMutationError = unknown;

/**
 * @summary 覆盖更新代表属性记录
 */
export const useUpdateRecord = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateRecord>>,
      TError,
      {
        delegateId: string;
        recordId: string;
        data: DelegateAttrRecordUpsertRequest;
      },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateRecord>>,
  TError,
  {
    delegateId: string;
    recordId: string;
    data: DelegateAttrRecordUpsertRequest;
  },
  TContext
> => {
  return useMutation(getUpdateRecordMutationOptions(options), queryClient);
};
/**
 * 仅 SYS_ADMIN / DH / DM 可访问
 * @summary 删除代表属性记录
 */
export type deleteRecordResponse200 = {
  data: Blob;
  status: 200;
};

export type deleteRecordResponseSuccess = deleteRecordResponse200 & {
  headers: Headers;
};
export type deleteRecordResponse = deleteRecordResponseSuccess;

export const getDeleteRecordUrl = (delegateId: string, recordId: string) => {
  return `/api/delegate-attrs/delegates/${delegateId}/records/${recordId}`;
};

export const deleteRecord = async (
  delegateId: string,
  recordId: string,
  options?: RequestInit,
): Promise<deleteRecordResponse> => {
  return customInstance<deleteRecordResponse>(
    getDeleteRecordUrl(delegateId, recordId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getDeleteRecordMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteRecord>>,
    TError,
    { delegateId: string; recordId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteRecord>>,
  TError,
  { delegateId: string; recordId: string },
  TContext
> => {
  const mutationKey = ["deleteRecord"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteRecord>>,
    { delegateId: string; recordId: string }
  > = (props) => {
    const { delegateId, recordId } = props ?? {};

    return deleteRecord(delegateId, recordId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteRecordMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteRecord>>
>;

export type DeleteRecordMutationError = unknown;

/**
 * @summary 删除代表属性记录
 */
export const useDeleteRecord = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteRecord>>,
      TError,
      { delegateId: string; recordId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteRecord>>,
  TError,
  { delegateId: string; recordId: string },
  TContext
> => {
  return useMutation(getDeleteRecordMutationOptions(options), queryClient);
};
/**
 * 仅 SYS_ADMIN / DH / DM 可访问
 * @summary 更新属性配置
 */
export type updateConfigResponse200 = {
  data: Blob;
  status: 200;
};

export type updateConfigResponseSuccess = updateConfigResponse200 & {
  headers: Headers;
};
export type updateConfigResponse = updateConfigResponseSuccess;

export const getUpdateConfigUrl = (configId: string) => {
  return `/api/delegate-attrs/configs/${configId}`;
};

export const updateConfig = async (
  configId: string,
  delegateAttrConfigUpdateRequest: DelegateAttrConfigUpdateRequest,
  options?: RequestInit,
): Promise<updateConfigResponse> => {
  return customInstance<updateConfigResponse>(getUpdateConfigUrl(configId), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(delegateAttrConfigUpdateRequest),
  });
};

export const getUpdateConfigMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateConfig>>,
    TError,
    { configId: string; data: DelegateAttrConfigUpdateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateConfig>>,
  TError,
  { configId: string; data: DelegateAttrConfigUpdateRequest },
  TContext
> => {
  const mutationKey = ["updateConfig"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateConfig>>,
    { configId: string; data: DelegateAttrConfigUpdateRequest }
  > = (props) => {
    const { configId, data } = props ?? {};

    return updateConfig(configId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateConfigMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateConfig>>
>;
export type UpdateConfigMutationBody = DelegateAttrConfigUpdateRequest;
export type UpdateConfigMutationError = unknown;

/**
 * @summary 更新属性配置
 */
export const useUpdateConfig = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateConfig>>,
      TError,
      { configId: string; data: DelegateAttrConfigUpdateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateConfig>>,
  TError,
  { configId: string; data: DelegateAttrConfigUpdateRequest },
  TContext
> => {
  return useMutation(getUpdateConfigMutationOptions(options), queryClient);
};
/**
 * 支持代表多选和属性等值过滤
 * @summary 学团分页查询代表属性记录
 */
export type queryForManagementResponse200 = {
  data: Blob;
  status: 200;
};

export type queryForManagementResponseSuccess =
  queryForManagementResponse200 & {
    headers: Headers;
  };
export type queryForManagementResponse = queryForManagementResponseSuccess;

export const getQueryForManagementUrl = (params: QueryForManagementParams) => {
  const stringifiedParams = buildQueryString(params as Record<string, unknown>);

  return stringifiedParams.length > 0
    ? `/api/delegate-attrs/manage/query?${stringifiedParams}`
    : `/api/delegate-attrs/manage/query`;
};

export const queryForManagement = async (
  delegateAttrManageQueryRequest: DelegateAttrManageQueryRequest,
  params: QueryForManagementParams,
  options?: RequestInit,
): Promise<queryForManagementResponse> => {
  return customInstance<queryForManagementResponse>(
    getQueryForManagementUrl(params),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(delegateAttrManageQueryRequest),
    },
  );
};

export const getQueryForManagementMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof queryForManagement>>,
    TError,
    { data: DelegateAttrManageQueryRequest; params: QueryForManagementParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof queryForManagement>>,
  TError,
  { data: DelegateAttrManageQueryRequest; params: QueryForManagementParams },
  TContext
> => {
  const mutationKey = ["queryForManagement"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof queryForManagement>>,
    { data: DelegateAttrManageQueryRequest; params: QueryForManagementParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return queryForManagement(data, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type QueryForManagementMutationResult = NonNullable<
  Awaited<ReturnType<typeof queryForManagement>>
>;
export type QueryForManagementMutationBody = DelegateAttrManageQueryRequest;
export type QueryForManagementMutationError = unknown;

/**
 * @summary 学团分页查询代表属性记录
 */
export const useQueryForManagement = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof queryForManagement>>,
      TError,
      {
        data: DelegateAttrManageQueryRequest;
        params: QueryForManagementParams;
      },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof queryForManagement>>,
  TError,
  { data: DelegateAttrManageQueryRequest; params: QueryForManagementParams },
  TContext
> => {
  return useMutation(
    getQueryForManagementMutationOptions(options),
    queryClient,
  );
};
/**
 * 仅 SYS_ADMIN / DH / DM 可访问
 * @summary 为代表新增属性记录
 */
export type createRecordResponse200 = {
  data: Blob;
  status: 200;
};

export type createRecordResponseSuccess = createRecordResponse200 & {
  headers: Headers;
};
export type createRecordResponse = createRecordResponseSuccess;

export const getCreateRecordUrl = (delegateId: string) => {
  return `/api/delegate-attrs/delegates/${delegateId}/records`;
};

export const createRecord = async (
  delegateId: string,
  delegateAttrRecordUpsertRequest: DelegateAttrRecordUpsertRequest,
  options?: RequestInit,
): Promise<createRecordResponse> => {
  return customInstance<createRecordResponse>(getCreateRecordUrl(delegateId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(delegateAttrRecordUpsertRequest),
  });
};

export const getCreateRecordMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createRecord>>,
    TError,
    { delegateId: string; data: DelegateAttrRecordUpsertRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createRecord>>,
  TError,
  { delegateId: string; data: DelegateAttrRecordUpsertRequest },
  TContext
> => {
  const mutationKey = ["createRecord"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createRecord>>,
    { delegateId: string; data: DelegateAttrRecordUpsertRequest }
  > = (props) => {
    const { delegateId, data } = props ?? {};

    return createRecord(delegateId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateRecordMutationResult = NonNullable<
  Awaited<ReturnType<typeof createRecord>>
>;
export type CreateRecordMutationBody = DelegateAttrRecordUpsertRequest;
export type CreateRecordMutationError = unknown;

/**
 * @summary 为代表新增属性记录
 */
export const useCreateRecord = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createRecord>>,
      TError,
      { delegateId: string; data: DelegateAttrRecordUpsertRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createRecord>>,
  TError,
  { delegateId: string; data: DelegateAttrRecordUpsertRequest },
  TContext
> => {
  return useMutation(getCreateRecordMutationOptions(options), queryClient);
};
/**
 * 需要登录
 * @summary 获取当前会议属性配置
 */
export type listConfigsResponse200 = {
  data: Blob;
  status: 200;
};

export type listConfigsResponseSuccess = listConfigsResponse200 & {
  headers: Headers;
};
export type listConfigsResponse = listConfigsResponseSuccess;

export const getListConfigsUrl = () => {
  return `/api/delegate-attrs/configs`;
};

export const listConfigs = async (
  options?: RequestInit,
): Promise<listConfigsResponse> => {
  return customInstance<listConfigsResponse>(getListConfigsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListConfigsQueryKey = () => {
  return [`/api/delegate-attrs/configs`] as const;
};

export const getListConfigsQueryOptions = <
  TData = Awaited<ReturnType<typeof listConfigs>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listConfigs>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListConfigsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listConfigs>>> = ({
    signal,
  }) => listConfigs({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listConfigs>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListConfigsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listConfigs>>
>;
export type ListConfigsQueryError = unknown;

export function useListConfigs<
  TData = Awaited<ReturnType<typeof listConfigs>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listConfigs>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listConfigs>>,
          TError,
          Awaited<ReturnType<typeof listConfigs>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListConfigs<
  TData = Awaited<ReturnType<typeof listConfigs>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listConfigs>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listConfigs>>,
          TError,
          Awaited<ReturnType<typeof listConfigs>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListConfigs<
  TData = Awaited<ReturnType<typeof listConfigs>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listConfigs>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 获取当前会议属性配置
 */

export function useListConfigs<
  TData = Awaited<ReturnType<typeof listConfigs>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listConfigs>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListConfigsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 仅 SYS_ADMIN / DH / DM 可访问
 * @summary 创建属性配置
 */
export type createConfigResponse200 = {
  data: Blob;
  status: 200;
};

export type createConfigResponseSuccess = createConfigResponse200 & {
  headers: Headers;
};
export type createConfigResponse = createConfigResponseSuccess;

export const getCreateConfigUrl = () => {
  return `/api/delegate-attrs/configs`;
};

export const createConfig = async (
  delegateAttrConfigCreateRequest: DelegateAttrConfigCreateRequest,
  options?: RequestInit,
): Promise<createConfigResponse> => {
  return customInstance<createConfigResponse>(getCreateConfigUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(delegateAttrConfigCreateRequest),
  });
};

export const getCreateConfigMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createConfig>>,
    TError,
    { data: DelegateAttrConfigCreateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createConfig>>,
  TError,
  { data: DelegateAttrConfigCreateRequest },
  TContext
> => {
  const mutationKey = ["createConfig"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createConfig>>,
    { data: DelegateAttrConfigCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createConfig(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateConfigMutationResult = NonNullable<
  Awaited<ReturnType<typeof createConfig>>
>;
export type CreateConfigMutationBody = DelegateAttrConfigCreateRequest;
export type CreateConfigMutationError = unknown;

/**
 * @summary 创建属性配置
 */
export const useCreateConfig = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createConfig>>,
      TError,
      { data: DelegateAttrConfigCreateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createConfig>>,
  TError,
  { data: DelegateAttrConfigCreateRequest },
  TContext
> => {
  return useMutation(getCreateConfigMutationOptions(options), queryClient);
};
/**
 * 仅 DELEGATE 可访问
 * @summary 代表查询自己的属性记录
 */
export type listMyRecordsResponse200 = {
  data: Blob;
  status: 200;
};

export type listMyRecordsResponseSuccess = listMyRecordsResponse200 & {
  headers: Headers;
};
export type listMyRecordsResponse = listMyRecordsResponseSuccess;

export const getListMyRecordsUrl = (params: ListMyRecordsParams) => {
  const stringifiedParams = buildQueryString(params as Record<string, unknown>);

  return stringifiedParams.length > 0
    ? `/api/delegate-attrs/my-records?${stringifiedParams}`
    : `/api/delegate-attrs/my-records`;
};

export const listMyRecords = async (
  params: ListMyRecordsParams,
  options?: RequestInit,
): Promise<listMyRecordsResponse> => {
  return customInstance<listMyRecordsResponse>(getListMyRecordsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListMyRecordsQueryKey = (params?: ListMyRecordsParams) => {
  return [
    `/api/delegate-attrs/my-records`,
    ...(params ? [params] : []),
  ] as const;
};

export const getListMyRecordsQueryOptions = <
  TData = Awaited<ReturnType<typeof listMyRecords>>,
  TError = unknown,
>(
  params: ListMyRecordsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMyRecords>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListMyRecordsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listMyRecords>>> = ({
    signal,
  }) => listMyRecords(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listMyRecords>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListMyRecordsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listMyRecords>>
>;
export type ListMyRecordsQueryError = unknown;

export function useListMyRecords<
  TData = Awaited<ReturnType<typeof listMyRecords>>,
  TError = unknown,
>(
  params: ListMyRecordsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMyRecords>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMyRecords>>,
          TError,
          Awaited<ReturnType<typeof listMyRecords>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListMyRecords<
  TData = Awaited<ReturnType<typeof listMyRecords>>,
  TError = unknown,
>(
  params: ListMyRecordsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMyRecords>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMyRecords>>,
          TError,
          Awaited<ReturnType<typeof listMyRecords>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListMyRecords<
  TData = Awaited<ReturnType<typeof listMyRecords>>,
  TError = unknown,
>(
  params: ListMyRecordsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMyRecords>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 代表查询自己的属性记录
 */

export function useListMyRecords<
  TData = Awaited<ReturnType<typeof listMyRecords>>,
  TError = unknown,
>(
  params: ListMyRecordsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMyRecords>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListMyRecordsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
