/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Asya Backend API
 * API documentation for Asya Backend application
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetAllParams,
  GetAllSecretInConferenceParams,
  GetSecretMessagesParams,
  MessageCreateRequest,
  MessageUpdateRequest,
} from "../asyaBackendAPI.schemas";

import { customInstance } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 查看消息及完整内容。所有登录用户可查看。若消息为secret则检查请求者是否在receivers列表。
 * @summary 查询单条消息详情
 */
export type getOneResponse200 = {
  data: Blob;
  status: 200;
};

export type getOneResponseSuccess = getOneResponse200 & {
  headers: Headers;
};
export type getOneResponse = getOneResponseSuccess;

export const getGetOneUrl = (uuid: string) => {
  return `/api/messages/${uuid}`;
};

export const getOne = async (
  uuid: string,
  options?: RequestInit,
): Promise<getOneResponse> => {
  return customInstance<getOneResponse>(getGetOneUrl(uuid), {
    ...options,
    method: "GET",
  });
};

export const getGetOneQueryKey = (uuid: string) => {
  return [`/api/messages/${uuid}`] as const;
};

export const getGetOneQueryOptions = <
  TData = Awaited<ReturnType<typeof getOne>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOne>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOneQueryKey(uuid);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOne>>> = ({
    signal,
  }) => getOne(uuid, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!uuid,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getOne>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetOneQueryResult = NonNullable<Awaited<ReturnType<typeof getOne>>>;
export type GetOneQueryError = unknown;

export function useGetOne<
  TData = Awaited<ReturnType<typeof getOne>>,
  TError = unknown,
>(
  uuid: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOne>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOne>>,
          TError,
          Awaited<ReturnType<typeof getOne>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOne<
  TData = Awaited<ReturnType<typeof getOne>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOne>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOne>>,
          TError,
          Awaited<ReturnType<typeof getOne>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOne<
  TData = Awaited<ReturnType<typeof getOne>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOne>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询单条消息详情
 */

export function useGetOne<
  TData = Awaited<ReturnType<typeof getOne>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOne>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOneQueryOptions(uuid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * DH、DM、SYS_ADMIN 可更新
 * @summary 更新消息
 */
export type updateResponse200 = {
  data: Blob;
  status: 200;
};

export type updateResponseSuccess = updateResponse200 & {
  headers: Headers;
};
export type updateResponse = updateResponseSuccess;

export const getUpdateUrl = (uuid: string) => {
  return `/api/messages/${uuid}`;
};

export const update = async (
  uuid: string,
  messageUpdateRequest: MessageUpdateRequest,
  options?: RequestInit,
): Promise<updateResponse> => {
  return customInstance<updateResponse>(getUpdateUrl(uuid), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(messageUpdateRequest),
  });
};

export const getUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof update>>,
    TError,
    { uuid: string; data: MessageUpdateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof update>>,
  TError,
  { uuid: string; data: MessageUpdateRequest },
  TContext
> => {
  const mutationKey = ["update"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof update>>,
    { uuid: string; data: MessageUpdateRequest }
  > = (props) => {
    const { uuid, data } = props ?? {};

    return update(uuid, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof update>>
>;
export type UpdateMutationBody = MessageUpdateRequest;
export type UpdateMutationError = unknown;

/**
 * @summary 更新消息
 */
export const useUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof update>>,
      TError,
      { uuid: string; data: MessageUpdateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof update>>,
  TError,
  { uuid: string; data: MessageUpdateRequest },
  TContext
> => {
  return useMutation(getUpdateMutationOptions(options), queryClient);
};
/**
 * DH、DM、SYS_ADMIN 可删除
 * @summary 删除消息
 */
export type _deleteResponse200 = {
  data: Blob;
  status: 200;
};

export type _deleteResponseSuccess = _deleteResponse200 & {
  headers: Headers;
};
export type _deleteResponse = _deleteResponseSuccess;

export const getDeleteUrl = (uuid: string) => {
  return `/api/messages/${uuid}`;
};

export const _delete = async (
  uuid: string,
  options?: RequestInit,
): Promise<_deleteResponse> => {
  return customInstance<_deleteResponse>(getDeleteUrl(uuid), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof _delete>>,
    TError,
    { uuid: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof _delete>>,
  TError,
  { uuid: string },
  TContext
> => {
  const mutationKey = ["_delete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof _delete>>,
    { uuid: string }
  > = (props) => {
    const { uuid } = props ?? {};

    return _delete(uuid, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type _DeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof _delete>>
>;

export type _DeleteMutationError = unknown;

/**
 * @summary 删除消息
 */
export const useDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof _delete>>,
      TError,
      { uuid: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof _delete>>,
  TError,
  { uuid: string },
  TContext
> => {
  return useMutation(getDeleteMutationOptions(options), queryClient);
};
/**
 * 分页查询，列表项省略 content 字段。查看用户当前所属 Conference 下的消息。
 * @summary 查询用户关联会议的所有消息
 */
export type getAllResponse200 = {
  data: Blob;
  status: 200;
};

export type getAllResponseSuccess = getAllResponse200 & {
  headers: Headers;
};
export type getAllResponse = getAllResponseSuccess;

export const getGetAllUrl = (params: GetAllParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/messages?${stringifiedParams}`
    : `/api/messages`;
};

export const getAll = async (
  params: GetAllParams,
  options?: RequestInit,
): Promise<getAllResponse> => {
  return customInstance<getAllResponse>(getGetAllUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetAllQueryKey = (params?: GetAllParams) => {
  return [`/api/messages`, ...(params ? [params] : [])] as const;
};

export const getGetAllQueryOptions = <
  TData = Awaited<ReturnType<typeof getAll>>,
  TError = unknown,
>(
  params: GetAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAll>>> = ({
    signal,
  }) => getAll(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllQueryResult = NonNullable<Awaited<ReturnType<typeof getAll>>>;
export type GetAllQueryError = unknown;

export function useGetAll<
  TData = Awaited<ReturnType<typeof getAll>>,
  TError = unknown,
>(
  params: GetAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAll>>,
          TError,
          Awaited<ReturnType<typeof getAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAll<
  TData = Awaited<ReturnType<typeof getAll>>,
  TError = unknown,
>(
  params: GetAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAll>>,
          TError,
          Awaited<ReturnType<typeof getAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAll<
  TData = Awaited<ReturnType<typeof getAll>>,
  TError = unknown,
>(
  params: GetAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询用户关联会议的所有消息
 */

export function useGetAll<
  TData = Awaited<ReturnType<typeof getAll>>,
  TError = unknown,
>(
  params: GetAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * DH、DM、SYS_ADMIN 可发布
 * @summary 发布消息
 */
export type create1Response200 = {
  data: Blob;
  status: 200;
};

export type create1ResponseSuccess = create1Response200 & {
  headers: Headers;
};
export type create1Response = create1ResponseSuccess;

export const getCreate1Url = () => {
  return `/api/messages`;
};

export const create1 = async (
  messageCreateRequest: MessageCreateRequest,
  options?: RequestInit,
): Promise<create1Response> => {
  return customInstance<create1Response>(getCreate1Url(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(messageCreateRequest),
  });
};

export const getCreate1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof create1>>,
    TError,
    { data: MessageCreateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof create1>>,
  TError,
  { data: MessageCreateRequest },
  TContext
> => {
  const mutationKey = ["create1"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof create1>>,
    { data: MessageCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return create1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type Create1MutationResult = NonNullable<
  Awaited<ReturnType<typeof create1>>
>;
export type Create1MutationBody = MessageCreateRequest;
export type Create1MutationError = unknown;

/**
 * @summary 发布消息
 */
export const useCreate1 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof create1>>,
      TError,
      { data: MessageCreateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof create1>>,
  TError,
  { data: MessageCreateRequest },
  TContext
> => {
  return useMutation(getCreate1MutationOptions(options), queryClient);
};
/**
 * 查看某条消息能被哪些用户查看。
 * @summary 查询消息可见用户
 */
export type getReceiversResponse200 = {
  data: Blob;
  status: 200;
};

export type getReceiversResponseSuccess = getReceiversResponse200 & {
  headers: Headers;
};
export type getReceiversResponse = getReceiversResponseSuccess;

export const getGetReceiversUrl = (uuid: string) => {
  return `/api/messages/${uuid}/receivers`;
};

export const getReceivers = async (
  uuid: string,
  options?: RequestInit,
): Promise<getReceiversResponse> => {
  return customInstance<getReceiversResponse>(getGetReceiversUrl(uuid), {
    ...options,
    method: "GET",
  });
};

export const getGetReceiversQueryKey = (uuid: string) => {
  return [`/api/messages/${uuid}/receivers`] as const;
};

export const getGetReceiversQueryOptions = <
  TData = Awaited<ReturnType<typeof getReceivers>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getReceivers>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetReceiversQueryKey(uuid);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getReceivers>>> = ({
    signal,
  }) => getReceivers(uuid, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!uuid,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getReceivers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReceiversQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReceivers>>
>;
export type GetReceiversQueryError = unknown;

export function useGetReceivers<
  TData = Awaited<ReturnType<typeof getReceivers>>,
  TError = unknown,
>(
  uuid: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getReceivers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReceivers>>,
          TError,
          Awaited<ReturnType<typeof getReceivers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReceivers<
  TData = Awaited<ReturnType<typeof getReceivers>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getReceivers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReceivers>>,
          TError,
          Awaited<ReturnType<typeof getReceivers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReceivers<
  TData = Awaited<ReturnType<typeof getReceivers>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getReceivers>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询消息可见用户
 */

export function useGetReceivers<
  TData = Awaited<ReturnType<typeof getReceivers>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getReceivers>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetReceiversQueryOptions(uuid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 分页查询用户发送或接收的非对称消息。
 * @summary 查询用户的非对称消息
 */
export type getSecretMessagesResponse200 = {
  data: Blob;
  status: 200;
};

export type getSecretMessagesResponseSuccess = getSecretMessagesResponse200 & {
  headers: Headers;
};
export type getSecretMessagesResponse = getSecretMessagesResponseSuccess;

export const getGetSecretMessagesUrl = (params: GetSecretMessagesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/messages/secret?${stringifiedParams}`
    : `/api/messages/secret`;
};

export const getSecretMessages = async (
  params: GetSecretMessagesParams,
  options?: RequestInit,
): Promise<getSecretMessagesResponse> => {
  return customInstance<getSecretMessagesResponse>(
    getGetSecretMessagesUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetSecretMessagesQueryKey = (
  params?: GetSecretMessagesParams,
) => {
  return [`/api/messages/secret`, ...(params ? [params] : [])] as const;
};

export const getGetSecretMessagesQueryOptions = <
  TData = Awaited<ReturnType<typeof getSecretMessages>>,
  TError = unknown,
>(
  params: GetSecretMessagesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSecretMessages>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetSecretMessagesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSecretMessages>>
  > = ({ signal }) => getSecretMessages(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSecretMessages>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSecretMessagesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSecretMessages>>
>;
export type GetSecretMessagesQueryError = unknown;

export function useGetSecretMessages<
  TData = Awaited<ReturnType<typeof getSecretMessages>>,
  TError = unknown,
>(
  params: GetSecretMessagesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSecretMessages>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSecretMessages>>,
          TError,
          Awaited<ReturnType<typeof getSecretMessages>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSecretMessages<
  TData = Awaited<ReturnType<typeof getSecretMessages>>,
  TError = unknown,
>(
  params: GetSecretMessagesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSecretMessages>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSecretMessages>>,
          TError,
          Awaited<ReturnType<typeof getSecretMessages>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSecretMessages<
  TData = Awaited<ReturnType<typeof getSecretMessages>>,
  TError = unknown,
>(
  params: GetSecretMessagesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSecretMessages>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询用户的非对称消息
 */

export function useGetSecretMessages<
  TData = Awaited<ReturnType<typeof getSecretMessages>>,
  TError = unknown,
>(
  params: GetSecretMessagesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSecretMessages>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetSecretMessagesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * DH、DM、SYS_ADMIN 可查询自己关联的conference下的所有非对称消息（is_secret为true）。可按senderId, receiverId, 标题keyword筛选
 * @summary 查询用户关联会议的所有非对称消息
 */
export type getAllSecretInConferenceResponse200 = {
  data: Blob;
  status: 200;
};

export type getAllSecretInConferenceResponseSuccess =
  getAllSecretInConferenceResponse200 & {
    headers: Headers;
  };
export type getAllSecretInConferenceResponse =
  getAllSecretInConferenceResponseSuccess;

export const getGetAllSecretInConferenceUrl = (
  params: GetAllSecretInConferenceParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/messages/secret/conference?${stringifiedParams}`
    : `/api/messages/secret/conference`;
};

export const getAllSecretInConference = async (
  params: GetAllSecretInConferenceParams,
  options?: RequestInit,
): Promise<getAllSecretInConferenceResponse> => {
  return customInstance<getAllSecretInConferenceResponse>(
    getGetAllSecretInConferenceUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetAllSecretInConferenceQueryKey = (
  params?: GetAllSecretInConferenceParams,
) => {
  return [
    `/api/messages/secret/conference`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetAllSecretInConferenceQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllSecretInConference>>,
  TError = unknown,
>(
  params: GetAllSecretInConferenceParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllSecretInConference>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAllSecretInConferenceQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAllSecretInConference>>
  > = ({ signal }) =>
    getAllSecretInConference(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllSecretInConference>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllSecretInConferenceQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllSecretInConference>>
>;
export type GetAllSecretInConferenceQueryError = unknown;

export function useGetAllSecretInConference<
  TData = Awaited<ReturnType<typeof getAllSecretInConference>>,
  TError = unknown,
>(
  params: GetAllSecretInConferenceParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllSecretInConference>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllSecretInConference>>,
          TError,
          Awaited<ReturnType<typeof getAllSecretInConference>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllSecretInConference<
  TData = Awaited<ReturnType<typeof getAllSecretInConference>>,
  TError = unknown,
>(
  params: GetAllSecretInConferenceParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllSecretInConference>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllSecretInConference>>,
          TError,
          Awaited<ReturnType<typeof getAllSecretInConference>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllSecretInConference<
  TData = Awaited<ReturnType<typeof getAllSecretInConference>>,
  TError = unknown,
>(
  params: GetAllSecretInConferenceParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllSecretInConference>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询用户关联会议的所有非对称消息
 */

export function useGetAllSecretInConference<
  TData = Awaited<ReturnType<typeof getAllSecretInConference>>,
  TError = unknown,
>(
  params: GetAllSecretInConferenceParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllSecretInConference>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllSecretInConferenceQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
