/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Asya Backend API
 * API documentation for Asya Backend application
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetAllParams,
  MessageCreateRequest,
  MessageUpdateRequest,
} from "../asyaBackendAPI.schemas";

import { customInstance } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 查看消息及完整内容。所有登录用户可查看。若消息为secret则抛出未实现错误。
 * @summary 查询单条消息详情
 */
export type getOneResponse200 = {
  data: Blob;
  status: 200;
};

export type getOneResponseSuccess = getOneResponse200 & {
  headers: Headers;
};
export type getOneResponse = getOneResponseSuccess;

export const getGetOneUrl = (uuid: string) => {
  return `/api/messages/${uuid}`;
};

export const getOne = async (
  uuid: string,
  options?: RequestInit,
): Promise<getOneResponse> => {
  return customInstance<getOneResponse>(getGetOneUrl(uuid), {
    ...options,
    method: "GET",
  });
};

export const getGetOneQueryKey = (uuid: string) => {
  return [`/api/messages/${uuid}`] as const;
};

export const getGetOneQueryOptions = <
  TData = Awaited<ReturnType<typeof getOne>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOne>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOneQueryKey(uuid);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOne>>> = ({
    signal,
  }) => getOne(uuid, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!uuid,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getOne>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetOneQueryResult = NonNullable<Awaited<ReturnType<typeof getOne>>>;
export type GetOneQueryError = unknown;

export function useGetOne<
  TData = Awaited<ReturnType<typeof getOne>>,
  TError = unknown,
>(
  uuid: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOne>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOne>>,
          TError,
          Awaited<ReturnType<typeof getOne>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOne<
  TData = Awaited<ReturnType<typeof getOne>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOne>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOne>>,
          TError,
          Awaited<ReturnType<typeof getOne>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOne<
  TData = Awaited<ReturnType<typeof getOne>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOne>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询单条消息详情
 */

export function useGetOne<
  TData = Awaited<ReturnType<typeof getOne>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOne>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOneQueryOptions(uuid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * DH、DM、SYS_ADMIN 可更新
 * @summary 更新消息
 */
export type updateResponse200 = {
  data: Blob;
  status: 200;
};

export type updateResponseSuccess = updateResponse200 & {
  headers: Headers;
};
export type updateResponse = updateResponseSuccess;

export const getUpdateUrl = (uuid: string) => {
  return `/api/messages/${uuid}`;
};

export const update = async (
  uuid: string,
  messageUpdateRequest: MessageUpdateRequest,
  options?: RequestInit,
): Promise<updateResponse> => {
  return customInstance<updateResponse>(getUpdateUrl(uuid), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(messageUpdateRequest),
  });
};

export const getUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof update>>,
    TError,
    { uuid: string; data: MessageUpdateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof update>>,
  TError,
  { uuid: string; data: MessageUpdateRequest },
  TContext
> => {
  const mutationKey = ["update"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof update>>,
    { uuid: string; data: MessageUpdateRequest }
  > = (props) => {
    const { uuid, data } = props ?? {};

    return update(uuid, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof update>>
>;
export type UpdateMutationBody = MessageUpdateRequest;
export type UpdateMutationError = unknown;

/**
 * @summary 更新消息
 */
export const useUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof update>>,
      TError,
      { uuid: string; data: MessageUpdateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof update>>,
  TError,
  { uuid: string; data: MessageUpdateRequest },
  TContext
> => {
  return useMutation(getUpdateMutationOptions(options), queryClient);
};
/**
 * 分页查询，列表项省略 content 字段。查看用户当前所属 Conference 下的消息。
 * @summary 查询用户关联会议的所有消息
 */
export type getAllResponse200 = {
  data: Blob;
  status: 200;
};

export type getAllResponseSuccess = getAllResponse200 & {
  headers: Headers;
};
export type getAllResponse = getAllResponseSuccess;

export const getGetAllUrl = (params: GetAllParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/messages?${stringifiedParams}`
    : `/api/messages`;
};

export const getAll = async (
  params: GetAllParams,
  options?: RequestInit,
): Promise<getAllResponse> => {
  return customInstance<getAllResponse>(getGetAllUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetAllQueryKey = (params?: GetAllParams) => {
  return [`/api/messages`, ...(params ? [params] : [])] as const;
};

export const getGetAllQueryOptions = <
  TData = Awaited<ReturnType<typeof getAll>>,
  TError = unknown,
>(
  params: GetAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAll>>> = ({
    signal,
  }) => getAll(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllQueryResult = NonNullable<Awaited<ReturnType<typeof getAll>>>;
export type GetAllQueryError = unknown;

export function useGetAll<
  TData = Awaited<ReturnType<typeof getAll>>,
  TError = unknown,
>(
  params: GetAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAll>>,
          TError,
          Awaited<ReturnType<typeof getAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAll<
  TData = Awaited<ReturnType<typeof getAll>>,
  TError = unknown,
>(
  params: GetAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAll>>,
          TError,
          Awaited<ReturnType<typeof getAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAll<
  TData = Awaited<ReturnType<typeof getAll>>,
  TError = unknown,
>(
  params: GetAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询用户关联会议的所有消息
 */

export function useGetAll<
  TData = Awaited<ReturnType<typeof getAll>>,
  TError = unknown,
>(
  params: GetAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * DH、DM、SYS_ADMIN 可发布
 * @summary 发布消息
 */
export type create1Response200 = {
  data: Blob;
  status: 200;
};

export type create1ResponseSuccess = create1Response200 & {
  headers: Headers;
};
export type create1Response = create1ResponseSuccess;

export const getCreate1Url = () => {
  return `/api/messages`;
};

export const create1 = async (
  messageCreateRequest: MessageCreateRequest,
  options?: RequestInit,
): Promise<create1Response> => {
  return customInstance<create1Response>(getCreate1Url(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(messageCreateRequest),
  });
};

export const getCreate1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof create1>>,
    TError,
    { data: MessageCreateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof create1>>,
  TError,
  { data: MessageCreateRequest },
  TContext
> => {
  const mutationKey = ["create1"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof create1>>,
    { data: MessageCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return create1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type Create1MutationResult = NonNullable<
  Awaited<ReturnType<typeof create1>>
>;
export type Create1MutationBody = MessageCreateRequest;
export type Create1MutationError = unknown;

/**
 * @summary 发布消息
 */
export const useCreate1 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof create1>>,
      TError,
      { data: MessageCreateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof create1>>,
  TError,
  { data: MessageCreateRequest },
  TContext
> => {
  return useMutation(getCreate1MutationOptions(options), queryClient);
};
