/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Asya Backend API
 * API documentation for Asya Backend application
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type helloWorldResponse200 = {
  data: Blob;
  status: 200;
};

export type helloWorldResponseSuccess = helloWorldResponse200 & {
  headers: Headers;
};
export type helloWorldResponse = helloWorldResponseSuccess;

export const getHelloWorldUrl = () => {
  return `/api/hello`;
};

export const helloWorld = async (
  options?: RequestInit,
): Promise<helloWorldResponse> => {
  return customInstance<helloWorldResponse>(getHelloWorldUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHelloWorldQueryKey = () => {
  return [`/api/hello`] as const;
};

export const getHelloWorldQueryOptions = <
  TData = Awaited<ReturnType<typeof helloWorld>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof helloWorld>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHelloWorldQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof helloWorld>>> = ({
    signal,
  }) => helloWorld({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof helloWorld>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HelloWorldQueryResult = NonNullable<
  Awaited<ReturnType<typeof helloWorld>>
>;
export type HelloWorldQueryError = unknown;

export function useHelloWorld<
  TData = Awaited<ReturnType<typeof helloWorld>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof helloWorld>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof helloWorld>>,
          TError,
          Awaited<ReturnType<typeof helloWorld>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHelloWorld<
  TData = Awaited<ReturnType<typeof helloWorld>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof helloWorld>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof helloWorld>>,
          TError,
          Awaited<ReturnType<typeof helloWorld>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHelloWorld<
  TData = Awaited<ReturnType<typeof helloWorld>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof helloWorld>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useHelloWorld<
  TData = Awaited<ReturnType<typeof helloWorld>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof helloWorld>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getHelloWorldQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
