spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/asya}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:asya}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB       # 单个文件最大限制
      max-request-size: 50MB   # 单次请求的总大小限制（包含多个文件和参数）

logging:
  level:
    root: WARN
