/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Asya Backend API
 * API documentation for Asya Backend application
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  UserGroupMembersRequest,
  UserGroupRequest,
} from "../asyaBackendAPI.schemas";

import { customInstance } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 需要登录
 * @summary 获取用户组详情
 */
export type getUserGroupResponse200 = {
  data: Blob;
  status: 200;
};

export type getUserGroupResponseSuccess = getUserGroupResponse200 & {
  headers: Headers;
};
export type getUserGroupResponse = getUserGroupResponseSuccess;

export const getGetUserGroupUrl = (id: number) => {
  return `/api/user-groups/${id}`;
};

export const getUserGroup = async (
  id: number,
  options?: RequestInit,
): Promise<getUserGroupResponse> => {
  return customInstance<getUserGroupResponse>(getGetUserGroupUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetUserGroupQueryKey = (id: number) => {
  return [`/api/user-groups/${id}`] as const;
};

export const getGetUserGroupQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserGroup>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserGroup>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserGroupQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserGroup>>> = ({
    signal,
  }) => getUserGroup(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserGroup>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserGroupQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserGroup>>
>;
export type GetUserGroupQueryError = unknown;

export function useGetUserGroup<
  TData = Awaited<ReturnType<typeof getUserGroup>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserGroup>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserGroup>>,
          TError,
          Awaited<ReturnType<typeof getUserGroup>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserGroup<
  TData = Awaited<ReturnType<typeof getUserGroup>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserGroup>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserGroup>>,
          TError,
          Awaited<ReturnType<typeof getUserGroup>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserGroup<
  TData = Awaited<ReturnType<typeof getUserGroup>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserGroup>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 获取用户组详情
 */

export function useGetUserGroup<
  TData = Awaited<ReturnType<typeof getUserGroup>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserGroup>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserGroupQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 需要 DH / DM / SYS_ADMIN 角色
 * @summary 更新用户组名称
 */
export type updateUserGroupResponse200 = {
  data: Blob;
  status: 200;
};

export type updateUserGroupResponseSuccess = updateUserGroupResponse200 & {
  headers: Headers;
};
export type updateUserGroupResponse = updateUserGroupResponseSuccess;

export const getUpdateUserGroupUrl = (id: number) => {
  return `/api/user-groups/${id}`;
};

export const updateUserGroup = async (
  id: number,
  userGroupRequest: UserGroupRequest,
  options?: RequestInit,
): Promise<updateUserGroupResponse> => {
  return customInstance<updateUserGroupResponse>(getUpdateUserGroupUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userGroupRequest),
  });
};

export const getUpdateUserGroupMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUserGroup>>,
    TError,
    { id: number; data: UserGroupRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUserGroup>>,
  TError,
  { id: number; data: UserGroupRequest },
  TContext
> => {
  const mutationKey = ["updateUserGroup"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUserGroup>>,
    { id: number; data: UserGroupRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateUserGroup(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUserGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUserGroup>>
>;
export type UpdateUserGroupMutationBody = UserGroupRequest;
export type UpdateUserGroupMutationError = unknown;

/**
 * @summary 更新用户组名称
 */
export const useUpdateUserGroup = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUserGroup>>,
      TError,
      { id: number; data: UserGroupRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateUserGroup>>,
  TError,
  { id: number; data: UserGroupRequest },
  TContext
> => {
  return useMutation(getUpdateUserGroupMutationOptions(options), queryClient);
};
/**
 * 需要 DH / DM / SYS_ADMIN 角色
 * @summary 删除用户组
 */
export type deleteUserGroupResponse200 = {
  data: Blob;
  status: 200;
};

export type deleteUserGroupResponseSuccess = deleteUserGroupResponse200 & {
  headers: Headers;
};
export type deleteUserGroupResponse = deleteUserGroupResponseSuccess;

export const getDeleteUserGroupUrl = (id: number) => {
  return `/api/user-groups/${id}`;
};

export const deleteUserGroup = async (
  id: number,
  options?: RequestInit,
): Promise<deleteUserGroupResponse> => {
  return customInstance<deleteUserGroupResponse>(getDeleteUserGroupUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteUserGroupMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteUserGroup>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteUserGroup>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteUserGroup"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteUserGroup>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteUserGroup(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteUserGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUserGroup>>
>;

export type DeleteUserGroupMutationError = unknown;

/**
 * @summary 删除用户组
 */
export const useDeleteUserGroup = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteUserGroup>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteUserGroup>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteUserGroupMutationOptions(options), queryClient);
};
/**
 * 需要登录
 * @summary 获取所有用户组
 */
export type getAllUserGroupsResponse200 = {
  data: Blob;
  status: 200;
};

export type getAllUserGroupsResponseSuccess = getAllUserGroupsResponse200 & {
  headers: Headers;
};
export type getAllUserGroupsResponse = getAllUserGroupsResponseSuccess;

export const getGetAllUserGroupsUrl = () => {
  return `/api/user-groups`;
};

export const getAllUserGroups = async (
  options?: RequestInit,
): Promise<getAllUserGroupsResponse> => {
  return customInstance<getAllUserGroupsResponse>(getGetAllUserGroupsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetAllUserGroupsQueryKey = () => {
  return [`/api/user-groups`] as const;
};

export const getGetAllUserGroupsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllUserGroups>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAllUserGroups>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllUserGroupsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAllUserGroups>>
  > = ({ signal }) => getAllUserGroups({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllUserGroups>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllUserGroupsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllUserGroups>>
>;
export type GetAllUserGroupsQueryError = unknown;

export function useGetAllUserGroups<
  TData = Awaited<ReturnType<typeof getAllUserGroups>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllUserGroups>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllUserGroups>>,
          TError,
          Awaited<ReturnType<typeof getAllUserGroups>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllUserGroups<
  TData = Awaited<ReturnType<typeof getAllUserGroups>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllUserGroups>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllUserGroups>>,
          TError,
          Awaited<ReturnType<typeof getAllUserGroups>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllUserGroups<
  TData = Awaited<ReturnType<typeof getAllUserGroups>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllUserGroups>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 获取所有用户组
 */

export function useGetAllUserGroups<
  TData = Awaited<ReturnType<typeof getAllUserGroups>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllUserGroups>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllUserGroupsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 需要 DH / DM / SYS_ADMIN 角色
 * @summary 创建用户组
 */
export type createUserGroupResponse200 = {
  data: Blob;
  status: 200;
};

export type createUserGroupResponseSuccess = createUserGroupResponse200 & {
  headers: Headers;
};
export type createUserGroupResponse = createUserGroupResponseSuccess;

export const getCreateUserGroupUrl = () => {
  return `/api/user-groups`;
};

export const createUserGroup = async (
  userGroupRequest: UserGroupRequest,
  options?: RequestInit,
): Promise<createUserGroupResponse> => {
  return customInstance<createUserGroupResponse>(getCreateUserGroupUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userGroupRequest),
  });
};

export const getCreateUserGroupMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createUserGroup>>,
    TError,
    { data: UserGroupRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createUserGroup>>,
  TError,
  { data: UserGroupRequest },
  TContext
> => {
  const mutationKey = ["createUserGroup"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createUserGroup>>,
    { data: UserGroupRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createUserGroup(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateUserGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof createUserGroup>>
>;
export type CreateUserGroupMutationBody = UserGroupRequest;
export type CreateUserGroupMutationError = unknown;

/**
 * @summary 创建用户组
 */
export const useCreateUserGroup = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createUserGroup>>,
      TError,
      { data: UserGroupRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createUserGroup>>,
  TError,
  { data: UserGroupRequest },
  TContext
> => {
  return useMutation(getCreateUserGroupMutationOptions(options), queryClient);
};
/**
 * 需要 DH / DM / SYS_ADMIN 角色
 * @summary 设置用户组成员（全量替换）
 */
export type setGroupMembersResponse200 = {
  data: Blob;
  status: 200;
};

export type setGroupMembersResponseSuccess = setGroupMembersResponse200 & {
  headers: Headers;
};
export type setGroupMembersResponse = setGroupMembersResponseSuccess;

export const getSetGroupMembersUrl = (id: number) => {
  return `/api/user-groups/${id}/users`;
};

export const setGroupMembers = async (
  id: number,
  userGroupMembersRequest: UserGroupMembersRequest,
  options?: RequestInit,
): Promise<setGroupMembersResponse> => {
  return customInstance<setGroupMembersResponse>(getSetGroupMembersUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userGroupMembersRequest),
  });
};

export const getSetGroupMembersMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof setGroupMembers>>,
    TError,
    { id: number; data: UserGroupMembersRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof setGroupMembers>>,
  TError,
  { id: number; data: UserGroupMembersRequest },
  TContext
> => {
  const mutationKey = ["setGroupMembers"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof setGroupMembers>>,
    { id: number; data: UserGroupMembersRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return setGroupMembers(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SetGroupMembersMutationResult = NonNullable<
  Awaited<ReturnType<typeof setGroupMembers>>
>;
export type SetGroupMembersMutationBody = UserGroupMembersRequest;
export type SetGroupMembersMutationError = unknown;

/**
 * @summary 设置用户组成员（全量替换）
 */
export const useSetGroupMembers = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof setGroupMembers>>,
      TError,
      { id: number; data: UserGroupMembersRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof setGroupMembers>>,
  TError,
  { id: number; data: UserGroupMembersRequest },
  TContext
> => {
  return useMutation(getSetGroupMembersMutationOptions(options), queryClient);
};
/**
 * 需要 DH / DM / SYS_ADMIN 角色
 * @summary 从用户组移除成员
 */
export type removeUserFromGroupResponse200 = {
  data: Blob;
  status: 200;
};

export type removeUserFromGroupResponseSuccess =
  removeUserFromGroupResponse200 & {
    headers: Headers;
  };
export type removeUserFromGroupResponse = removeUserFromGroupResponseSuccess;

export const getRemoveUserFromGroupUrl = (id: number, uuid: string) => {
  return `/api/user-groups/${id}/users/${uuid}`;
};

export const removeUserFromGroup = async (
  id: number,
  uuid: string,
  options?: RequestInit,
): Promise<removeUserFromGroupResponse> => {
  return customInstance<removeUserFromGroupResponse>(
    getRemoveUserFromGroupUrl(id, uuid),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getRemoveUserFromGroupMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeUserFromGroup>>,
    TError,
    { id: number; uuid: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeUserFromGroup>>,
  TError,
  { id: number; uuid: string },
  TContext
> => {
  const mutationKey = ["removeUserFromGroup"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeUserFromGroup>>,
    { id: number; uuid: string }
  > = (props) => {
    const { id, uuid } = props ?? {};

    return removeUserFromGroup(id, uuid, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveUserFromGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeUserFromGroup>>
>;

export type RemoveUserFromGroupMutationError = unknown;

/**
 * @summary 从用户组移除成员
 */
export const useRemoveUserFromGroup = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof removeUserFromGroup>>,
      TError,
      { id: number; uuid: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof removeUserFromGroup>>,
  TError,
  { id: number; uuid: string },
  TContext
> => {
  return useMutation(
    getRemoveUserFromGroupMutationOptions(options),
    queryClient,
  );
};
