/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Asya Backend API
 * API documentation for Asya Backend application
 * OpenAPI spec version: 1.0.0
 */
/**
 * 用户角色
 */
export type UserUpdateRequestRole =
  (typeof UserUpdateRequestRole)[keyof typeof UserUpdateRequestRole];

export const UserUpdateRequestRole = {
  DELEGATE: "DELEGATE",
  DM: "DM",
  DH: "DH",
  SYS_ADMIN: "SYS_ADMIN",
} as const;

/**
 * 用户更新请求
 */
export interface UserUpdateRequest {
  /** 用户昵称 */
  name?: string;
  /** 用户密码 */
  password?: string;
  /** 用户角色 */
  role?: UserUpdateRequestRole;
}

/**
 * 用户角色
 */
export type UserInfoResponseRole =
  (typeof UserInfoResponseRole)[keyof typeof UserInfoResponseRole];

export const UserInfoResponseRole = {
  DELEGATE: "DELEGATE",
  DM: "DM",
  DH: "DH",
  SYS_ADMIN: "SYS_ADMIN",
} as const;

/**
 * 用户信息响应
 */
export interface UserInfoResponse {
  /** 用户ID */
  uuid: string;
  /** 用户昵称 */
  name: string;
  /** 用户角色 */
  role: UserInfoResponseRole;
}

/**
 * 统一接口返回结构
 */
export interface ResultUserInfoResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: UserInfoResponse;
}

/**
 * 会议状态
 */
export type ConferenceRequestStatus =
  (typeof ConferenceRequestStatus)[keyof typeof ConferenceRequestStatus];

export const ConferenceRequestStatus = {
  PREPARING: "PREPARING",
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
} as const;

/**
 * 会议信息请求
 */
export interface ConferenceRequest {
  /** 会议名称 */
  name: string;
  /** 会议描述 */
  description: string;
  /** 会议状态 */
  status?: ConferenceRequestStatus;
}

/**
 * 会议状态
 */
export type ConferenceResponseStatus =
  (typeof ConferenceResponseStatus)[keyof typeof ConferenceResponseStatus];

export const ConferenceResponseStatus = {
  PREPARING: "PREPARING",
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
} as const;

/**
 * 会期状态
 */
export type ConferenceSessionResponseStatus =
  (typeof ConferenceSessionResponseStatus)[keyof typeof ConferenceSessionResponseStatus];

export const ConferenceSessionResponseStatus = {
  PREPARE: "PREPARE",
  RUNNING: "RUNNING",
  PAUSED: "PAUSED",
  ENDED: "ENDED",
} as const;

/**
 * 会期响应信息
 */
export interface ConferenceSessionResponse {
  /** 会期ID */
  uuid: string;
  /** 所属会议ID */
  conferenceId: string;
  /** 会期名称 */
  name: string;
  /** 会期描述 */
  description?: string;
  /** 会期状态 */
  status: ConferenceSessionResponseStatus;
}

/**
 * 会议信息响应
 */
export interface ConferenceResponse {
  /** 会议ID */
  uuid: string;
  /** 会议名称 */
  name: string;
  /** 会议描述 */
  description: string;
  /** 会议状态 */
  status: ConferenceResponseStatus;
  /** 当前会期 */
  currentSession?: ConferenceSessionResponse;
}

/**
 * 统一接口返回结构
 */
export interface ResultConferenceResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: ConferenceResponse;
}

/**
 * 会期状态
 */
export type ConferenceSessionRequestStatus =
  (typeof ConferenceSessionRequestStatus)[keyof typeof ConferenceSessionRequestStatus];

export const ConferenceSessionRequestStatus = {
  PREPARE: "PREPARE",
  RUNNING: "RUNNING",
  PAUSED: "PAUSED",
  ENDED: "ENDED",
} as const;

/**
 * 创建/修改会期请求
 */
export interface ConferenceSessionRequest {
  /** 会期名称 */
  name: string;
  /** 会期描述 */
  description?: string;
  /** 会期状态 */
  status: ConferenceSessionRequestStatus;
}

/**
 * 统一接口返回结构
 */
export interface ResultConferenceSessionResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: ConferenceSessionResponse;
}

/**
 * 用户角色
 */
export type UserRegistrationRequestRole =
  (typeof UserRegistrationRequestRole)[keyof typeof UserRegistrationRequestRole];

export const UserRegistrationRequestRole = {
  DELEGATE: "DELEGATE",
  DM: "DM",
  DH: "DH",
  SYS_ADMIN: "SYS_ADMIN",
} as const;

/**
 * 用户注册请求信息
 */
export interface UserRegistrationRequest {
  /** 用户昵称 */
  name: string;
  /** 用户密码 */
  password: string;
  /** 用户角色 */
  role: UserRegistrationRequestRole;
}

/**
 * 用户角色
 */
export type UserResponseRole =
  (typeof UserResponseRole)[keyof typeof UserResponseRole];

export const UserResponseRole = {
  DELEGATE: "DELEGATE",
  DM: "DM",
  DH: "DH",
  SYS_ADMIN: "SYS_ADMIN",
} as const;

/**
 * 用户响应信息
 */
export interface UserResponse {
  /** 用户ID */
  uuid: string;
  /** 用户昵称 */
  name: string;
  /** 用户角色 */
  role: UserResponseRole;
  /** JWT Token */
  token: string;
}

/**
 * 统一接口返回结构
 */
export interface ResultUserResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: UserResponse;
}

export interface TimeUpdateRequest {
  /** 会期ID */
  sessionId: string;
  /** 时间流速 */
  timeRatio: number;
}

/**
 * 时间锚点响应
 */
export interface TimeAnchorResponse {
  /** ID */
  id: number;
  /** 会期ID */
  sessionId?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 锚点物理时间 */
  anchorRealTime?: string;
  /** 锚点游戏时间 */
  anchorGameTime?: string;
  /** 流速 */
  timeRatio?: number;
  /** 是否当前生效 */
  isCurrent: boolean;
}

/**
 * 统一接口返回结构
 */
export interface ResultTimeAnchorResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: TimeAnchorResponse;
}

export interface TimeJumpRequest {
  /** 会期ID */
  sessionId: string;
  /** 目标游戏时间 */
  targetGameTime: string;
  /** 时间流速 */
  timeRatio: number;
}

/**
 * 用户关联会议请求
 */
export interface ConferenceAssignRequest {
  /** 会议ID */
  conferenceUuid: string;
  /** 用户ID */
  userUuid: string;
}

/**
 * 统一接口返回结构
 */
export interface ResultListUserInfoResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: UserInfoResponse[];
}

/**
 * 统一接口返回结构
 */
export interface ResultListTimeAnchorResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: TimeAnchorResponse[];
}

export interface SseEmitter {
  timeout?: number;
}

export interface CurrentTimeResponse {
  /** 当前游戏时间 */
  currentGameTime: string;
}

/**
 * 统一接口返回结构
 */
export interface ResultCurrentTimeResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: CurrentTimeResponse;
}

/**
 * 统一接口返回结构
 */
export interface ResultString {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: string;
}

/**
 * 统一接口返回结构
 */
export interface ResultListConferenceSessionResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: ConferenceSessionResponse[];
}

/**
 * 统一接口返回结构
 */
export interface ResultListConferenceResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: ConferenceResponse[];
}
