/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Asya Backend API
 * API documentation for Asya Backend application
 * OpenAPI spec version: 1.0.0
 */
/**
 * 用户角色
 */
export type UserUpdateRequestRole =
  (typeof UserUpdateRequestRole)[keyof typeof UserUpdateRequestRole];

export const UserUpdateRequestRole = {
  DELEGATE: "DELEGATE",
  DM: "DM",
  DH: "DH",
  SYS_ADMIN: "SYS_ADMIN",
} as const;

/**
 * 用户更新请求
 */
export interface UserUpdateRequest {
  /** 用户昵称 */
  name?: string;
  /** 显示名称 */
  displayName?: string;
  /** 用户密码 */
  password?: string;
  /** 用户角色 */
  role?: UserUpdateRequestRole;
}

/**
 * 用户角色
 */
export type UserInfoResponseRole =
  (typeof UserInfoResponseRole)[keyof typeof UserInfoResponseRole];

export const UserInfoResponseRole = {
  DELEGATE: "DELEGATE",
  DM: "DM",
  DH: "DH",
  SYS_ADMIN: "SYS_ADMIN",
} as const;

/**
 * 用户信息响应
 */
export interface UserInfoResponse {
  /** 用户ID */
  uuid: string;
  /** 用户昵称 */
  name: string;
  /** 显示名称 */
  displayName?: string;
  /** 用户角色 */
  role: UserInfoResponseRole;
  /** 关联会议名称 */
  conferenceName?: string;
}

/**
 * 统一接口返回结构
 */
export interface ResultUserInfoResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: UserInfoResponse;
}

/**
 * 消息类型
 */
export type MessageUpdateRequestMsgType =
  (typeof MessageUpdateRequestMsgType)[keyof typeof MessageUpdateRequestMsgType];

export const MessageUpdateRequestMsgType = {
  EVENT: "EVENT",
  NEWS: "NEWS",
  CRISIS: "CRISIS",
  SECRET_LETTER: "SECRET_LETTER",
  WAR_REPORT: "WAR_REPORT",
} as const;

/**
 * 更新消息请求
 */
export interface MessageUpdateRequest {
  /** 标题 */
  title?: string;
  /** 内容 */
  content?: string;
  /** 摘要 */
  brief?: string;
  /** 消息类型 */
  msgType?: MessageUpdateRequestMsgType;
  /** 发布现实时间 */
  publishRealTime?: string;
  /** 发布游戏时间 */
  publishGameTime?: string;
  /** 是否加密 */
  isSecret?: boolean;
  /** 附件UUID列表(为空表示清空，null表示不修改) */
  attachmentUuids?: string[];
}

/**
 * 消息类型
 */
export type MessageResponseMsgType =
  (typeof MessageResponseMsgType)[keyof typeof MessageResponseMsgType];

export const MessageResponseMsgType = {
  EVENT: "EVENT",
  NEWS: "NEWS",
  CRISIS: "CRISIS",
  SECRET_LETTER: "SECRET_LETTER",
  WAR_REPORT: "WAR_REPORT",
} as const;

/**
 * 消息详情响应
 */
export interface MessageResponse {
  /** 消息UUID */
  uuid: string;
  /** 会议UUID */
  conferenceId: string;
  /** 发送者UUID */
  senderId?: string;
  /** 发送者名称 */
  senderName?: string;
  /** 标题 */
  title?: string;
  /** 摘要 */
  brief?: string;
  /** 内容(列表查询时为空) */
  content?: string;
  /** 消息类型 */
  msgType?: MessageResponseMsgType;
  /** 发布现实时间 */
  publishRealTime: string;
  /** 发布游戏时间 */
  publishGameTime: string;
  /** 是否加密 */
  isSecret: boolean;
  /** 是否有附件(仅详情返回) */
  hasAttachment?: boolean;
  /** 附件UUID列表(仅详情返回) */
  attachmentUuids?: string[];
}

/**
 * 统一接口返回结构
 */
export interface ResultMessageResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: MessageResponse;
}

/**
 * 会议状态
 */
export type ConferenceRequestStatus =
  (typeof ConferenceRequestStatus)[keyof typeof ConferenceRequestStatus];

export const ConferenceRequestStatus = {
  PREPARING: "PREPARING",
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
} as const;

/**
 * 会议信息请求
 */
export interface ConferenceRequest {
  /** 会议名称 */
  name: string;
  /** 会议描述 */
  description: string;
  /** 会议状态 */
  status?: ConferenceRequestStatus;
}

/**
 * 会议状态
 */
export type ConferenceResponseStatus =
  (typeof ConferenceResponseStatus)[keyof typeof ConferenceResponseStatus];

export const ConferenceResponseStatus = {
  PREPARING: "PREPARING",
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
} as const;

/**
 * 会议信息响应
 */
export interface ConferenceResponse {
  /** 会议ID */
  uuid: string;
  /** 会议名称 */
  name: string;
  /** 会议描述 */
  description: string;
  /** 会议状态 */
  status: ConferenceResponseStatus;
}

/**
 * 统一接口返回结构
 */
export interface ResultConferenceResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: ConferenceResponse;
}

/**
 * 统一接口返回结构
 */
export interface ResultUnit {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
}

/**
 * 统一接口返回结构
 */
export interface ResultBoolean {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: boolean;
}

/**
 * 用户角色
 */
export type UserRegistrationRequestRole =
  (typeof UserRegistrationRequestRole)[keyof typeof UserRegistrationRequestRole];

export const UserRegistrationRequestRole = {
  DELEGATE: "DELEGATE",
  DM: "DM",
  DH: "DH",
  SYS_ADMIN: "SYS_ADMIN",
} as const;

/**
 * 用户注册请求信息
 */
export interface UserRegistrationRequest {
  /** 用户昵称 */
  name: string;
  /** 显示名称 */
  displayName?: string;
  /** 用户密码 */
  password: string;
  /** 用户角色 */
  role: UserRegistrationRequestRole;
}

/**
 * 用户角色
 */
export type UserResponseRole =
  (typeof UserResponseRole)[keyof typeof UserResponseRole];

export const UserResponseRole = {
  DELEGATE: "DELEGATE",
  DM: "DM",
  DH: "DH",
  SYS_ADMIN: "SYS_ADMIN",
} as const;

/**
 * 用户响应信息
 */
export interface UserResponse {
  /** 用户ID */
  uuid: string;
  /** 用户昵称 */
  name: string;
  /** 显示名称 */
  displayName?: string;
  /** 用户角色 */
  role: UserResponseRole;
  /** JWT Token */
  token: string;
}

/**
 * 统一接口返回结构
 */
export interface ResultUserResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: UserResponse;
}

/**
 * 批量注册用户请求
 */
export interface BatchRegisterUserItem {
  /** 用户昵称 */
  name: string;
  /** 显示名称 */
  displayName?: string;
  /** 用户密码 */
  password: string;
}

/**
 * 批量注册请求
 */
export interface BatchRegisterRequest {
  /** 关联会议ID */
  conferenceId: string;
  /** 用户列表 */
  users: BatchRegisterUserItem[];
}

/**
 * 批量注册响应
 */
export interface BatchRegisterResponse {
  /** 成功注册的用户数量 */
  successCount: number;
  /** 注册成功的用户列表 */
  createdUsers: UserInfoResponse[];
}

/**
 * 统一接口返回结构
 */
export interface ResultBatchRegisterResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: BatchRegisterResponse;
}

export interface TimeUpdateRequest {
  /** 时间流速 */
  timeRatio: number;
}

/**
 * 时间锚点响应
 */
export interface TimeAnchorResponse {
  /** ID */
  id: number;
  /** 会议ID */
  conferenceId?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 锚点物理时间 */
  anchorRealTime?: string;
  /** 锚点游戏时间 */
  anchorGameTime?: string;
  /** 流速 */
  timeRatio?: number;
  /** 是否当前生效 */
  isCurrent: boolean;
}

/**
 * 统一接口返回结构
 */
export interface ResultTimeAnchorResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: TimeAnchorResponse;
}

export interface TimeJumpRequest {
  /** 目标游戏时间 */
  targetGameTime: string;
  /** 时间流速 */
  timeRatio: number;
}

/**
 * 消息类型: EVENT, NEWS, CRISIS, SECRET_LETTER, WAR_REPORT
 */
export type MessageCreateRequestMsgType =
  (typeof MessageCreateRequestMsgType)[keyof typeof MessageCreateRequestMsgType];

export const MessageCreateRequestMsgType = {
  EVENT: "EVENT",
  NEWS: "NEWS",
  CRISIS: "CRISIS",
  SECRET_LETTER: "SECRET_LETTER",
  WAR_REPORT: "WAR_REPORT",
} as const;

/**
 * 创建消息请求
 */
export interface MessageCreateRequest {
  /** 标题 */
  title: string;
  /** 内容(富文本) */
  content: string;
  /** 摘要(可选, 默认截取前30字) */
  brief?: string;
  /** 消息类型: EVENT, NEWS, CRISIS, SECRET_LETTER, WAR_REPORT */
  msgType: MessageCreateRequestMsgType;
  /** 发布现实时间(可选，默认为服务器当前时间) */
  publishRealTime?: string;
  /** 发布游戏时间 */
  publishGameTime: string;
  /** 是否加密(默认为false) */
  isSecret: boolean;
  /** 接收者ID列表(UUID), 当isSecret为true时有效 */
  receiverIds?: string[];
  /** 附件UUID列表 */
  attachmentUuids?: string[];
}

/**
 * 用户关联会议请求
 */
export interface ConferenceAssignRequest {
  /** 会议ID */
  conferenceUuid: string;
  /** 用户ID */
  userUuid: string;
}

/**
 * 上传附件响应
 */
export interface AttachmentUploadResponse {
  /** 附件UUID */
  uuid: string;
  /** 文件名(不含后缀) */
  fileName: string;
  /** 文件后缀 */
  fileType: string;
}

/**
 * 统一接口返回结构
 */
export interface ResultAttachmentUploadResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: AttachmentUploadResponse;
}

/**
 * 统一接口返回结构
 */
export interface ResultListUserInfoResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: UserInfoResponse[];
}

/**
 * 统一接口返回结构
 */
export interface ResultListTimeAnchorResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: TimeAnchorResponse[];
}

export interface CurrentTimeResponse {
  /** 当前游戏时间 */
  currentGameTime: string;
}

/**
 * 统一接口返回结构
 */
export interface ResultCurrentTimeResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: CurrentTimeResponse;
}

export interface Pageable {
  /** @minimum 0 */
  page?: number;
  /** @minimum 1 */
  size?: number;
  sort?: string[];
}

export interface Sortnull {
  empty?: boolean;
  unsorted?: boolean;
  sorted?: boolean;
}

export interface Pageablenull {
  offset?: number;
  sort?: Sortnull;
  unpaged?: boolean;
  paged?: boolean;
  pageNumber?: number;
  pageSize?: number;
}

export interface Pagenull {
  totalPages?: number;
  totalElements?: number;
  first?: boolean;
  last?: boolean;
  size?: number;
  content?: MessageResponse[];
  number?: number;
  sort?: Sortnull;
  pageable?: Pageablenull;
  numberOfElements?: number;
  empty?: boolean;
}

/**
 * 统一接口返回结构
 */
export interface ResultPageMessageResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: Pagenull;
}

/**
 * 统一接口返回结构
 */
export interface ResultString {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: string;
}

/**
 * 统一接口返回结构
 */
export interface ResultListConferenceResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: ConferenceResponse[];
}

/**
 * 关联目标类型
 */
export type AttachmentInfoResponseTargetType =
  (typeof AttachmentInfoResponseTargetType)[keyof typeof AttachmentInfoResponseTargetType];

export const AttachmentInfoResponseTargetType = {
  MESSAGE: "MESSAGE",
  DIRECTIVE: "DIRECTIVE",
} as const;

/**
 * 附件信息(不含BLOB)
 */
export interface AttachmentInfoResponse {
  /** 附件UUID */
  uuid: string;
  /** 文件名(不含后缀) */
  fileName: string;
  /** 文件后缀 */
  fileType: string;
  /** 文件大小(字节) */
  fileSize: number;
  /** 关联目标类型 */
  targetType?: AttachmentInfoResponseTargetType;
  /** 关联目标UUID */
  targetId?: string;
  /** 关联消息UUID */
  messageId?: string;
}

/**
 * 统一接口返回结构
 */
export interface ResultListAttachmentInfoResponse {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  data?: AttachmentInfoResponse[];
}

export type ResetPasswordBody = { [key: string]: string };

export type SetRegistrationSwitchParams = {
  allowed: boolean;
};

export type GetAllParams = {
  pageable: Pageable;
};

export type UploadBody = {
  file: Blob;
};

export type GetSecretMessagesParams = {
  pageable: Pageable;
};

export type GetAllSecretInConferenceParams = {
  senderId?: string;
  receiverId?: string;
  keyword?: string;
  pageable: Pageable;
};
