create table public.conferences
(
    uuid        uuid         not null
        primary key,
    description varchar(255),
    name        varchar(255) not null,
    status      varchar(255) not null
        constraint conferences_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PREPARING'::character varying, 'RUNNING'::character varying, 'COMPLETED'::character varying])::text[]))
);

alter table public.conferences
    owner to asya;

create table public.system_configs
(
    config_key   varchar(50)  not null
        primary key,
    description  varchar(255),
    config_value varchar(255) not null
);

alter table public.system_configs
    owner to asya;

create table public.time_anchors
(
    id               bigint generated by default as identity
        primary key,
    anchor_game_time varchar(255),
    anchor_real_time timestamp(6),
    is_current       boolean,
    time_ratio       numeric(10, 2),
    update_time      timestamp(6),
    conference_id    uuid not null
        constraint fko1cdj59ojnuofj8g9l6376p9r
            references public.conferences
);

alter table public.time_anchors
    owner to asya;

create table public.users
(
    uuid          uuid         not null
        primary key,
    display_name  varchar(255),
    name          varchar(255) not null,
    password      varchar(255) not null,
    role          varchar(255) not null
        constraint users_role_check
            check ((role)::text = ANY
                   ((ARRAY ['DELEGATE'::character varying, 'DM'::character varying, 'DH'::character varying, 'SYS_ADMIN'::character varying])::text[])),
    conference_id uuid
        constraint fk3krvvry8t7dak156f22oxfgfs
            references public.conferences
);

alter table public.users
    owner to asya;

create table public.messages
(
    uuid              uuid         not null
        primary key,
    brief             varchar(500),
    msg_content       text,
    is_secret         boolean,
    msg_type          varchar(20)
        constraint messages_msg_type_check
            check ((msg_type)::text = ANY
                   ((ARRAY ['EVENT'::character varying, 'NEWS'::character varying, 'CRISIS'::character varying, 'SECRET_LETTER'::character varying, 'WAR_REPORT'::character varying])::text[])),
    publish_game_time varchar(255) not null,
    publish_real_time timestamp(6) not null,
    title             varchar(200),
    conference_id     uuid
        constraint fkfxr9qkf9bum4tombxal163wv1
            references public.conferences,
    sender_id         uuid
        constraint fk4ui4nnwntodh6wjvck53dbk9m
            references public.users
);

alter table public.messages
    owner to asya;

create table public.attachments
(
    uuid        uuid         not null
        primary key,
    file_blob   oid          not null,
    file_name   varchar(255) not null,
    file_size   bigint       not null,
    file_type   varchar(20)  not null,
    target_id   uuid,
    target_type varchar(30),
    message_id  uuid
        constraint fkcf4ta8qdkixetfy7wnqfv3vkv
            references public.messages
);

alter table public.attachments
    owner to asya;

create index idx_attachment_message_id
    on public.attachments (message_id);

create index idx_attachment_target
    on public.attachments (target_type, target_id);

create table public.audit_logs
(
    id            bigint generated by default as identity
        primary key,
    action_type   varchar(64)  not null,
    actor_name    varchar(120),
    actor_uuid    uuid,
    actor_ip      varchar(45),
    request_method varchar(10),
    request_path  varchar(255),
    request_query varchar(1000),
    user_agent    varchar(300),
    resource_type varchar(80),
    resource_id   varchar(120),
    event_content text         not null,
    context_data  text,
    event_time    timestamp(6) not null,
    success       boolean      not null
);

alter table public.audit_logs
    owner to asya;

create index idx_audit_logs_event_time
    on public.audit_logs (event_time desc);

create index idx_audit_logs_action_type
    on public.audit_logs (action_type);

create index idx_audit_logs_actor_uuid
    on public.audit_logs (actor_uuid);

create table public.user_groups
(
    id         bigint generated by default as identity
        primary key,
    group_name varchar(120) not null
);

alter table public.user_groups
    owner to asya;

create table public.user_group_members
(
    group_id  bigint not null
        constraint fktojippg1wvsa2cybvlq4gbi4l
            references public.user_groups,
    user_uuid uuid   not null
        constraint fk1wco1flyu1yewhn4w5xcwhe5
            references public.users,
    primary key (group_id, user_uuid)
);

alter table public.user_group_members
    owner to asya;

create table public.message_receivers
(
    readable_at timestamp(6) not null,
    message_id  uuid         not null
        constraint fkqo0ye7kcad9rwk3al53u9m17
            references public.messages,
    user_id     uuid         not null
        constraint fkcvx3xtpr0ggley36ewhknghbs
            references public.users,
    primary key (message_id, user_id)
);

alter table public.message_receivers
    owner to asya;

create table public.instructions
(
    uuid                uuid         not null
        primary key,
    instruction_content text         not null,
    instruction_type    varchar(32)  not null
        constraint instructions_instruction_type_check
            check ((instruction_type)::text = ANY
                   ((ARRAY ['MILITARY'::character varying, 'DIPLOMACY'::character varying, 'INTERNAL'::character varying, 'OTHER'::character varying])::text[])),
    review_comment      text,
    reviewed_game_time  varchar(255),
    reviewed_real_time  timestamp(6),
    status              varchar(32)  not null
        constraint instructions_status_check
            check ((status)::text = ANY
                   ((ARRAY ['SUBMITTED'::character varying, 'IN_PROGRESS'::character varying, 'REJECTED'::character varying, 'FEEDBACKED'::character varying])::text[])),
    submit_game_time    varchar(255) not null,
    submit_real_time    timestamp(6) not null,
    title               varchar(200) not null,
    conference_id       uuid         not null
        constraint fk7bgblwt3nc9dq0eplbqcb7sxd
            references public.conferences,
    reviewed_by         uuid
        constraint fk80c3ym25y7aaww8iasdyyu0d4
            references public.users,
    submitter_id        uuid         not null
        constraint fkqd3pb3rb239fry3i1apyiih7
            references public.users
);

alter table public.instructions
    owner to asya;

create table public.rounds
(
    uuid              uuid         not null
        primary key,
    duration_seconds  bigint       not null,
    end_at            timestamp(6),
    is_current        boolean      not null,
    name              varchar(255) not null,
    remaining_seconds bigint       not null,
    status            varchar(255) not null
        constraint rounds_status_check
            check ((status)::text = ANY ((ARRAY ['RUNNING'::character varying, 'PAUSED'::character varying])::text[])),
    updated_at        timestamp(6) not null,
    conference_id     uuid         not null
        constraint fko9e2ki88g2jjiqxlabt1je88q
            references public.conferences,
    next_round_id     uuid
        constraint fk41xnioqopl6exymr5dmnyfr9s
            references public.rounds
);

alter table public.rounds
    owner to asya;

create index idx_round_conference_current
    on public.rounds (conference_id, is_current);

create index idx_round_end_at
    on public.rounds (end_at);

create table public.delegate_attr_configs
(
    id            uuid                 not null
        primary key,
    attr_key      varchar(80)          not null,
    attr_label    varchar(120)         not null,
    attr_type     varchar(16)          not null
        constraint delegate_attr_configs_attr_type_check
            check ((attr_type)::text = ANY ((ARRAY ['TEXT'::character varying, 'NUMBER'::character varying])::text[])),
    created_at    timestamp(6)         not null,
    created_by    uuid,
    enabled       boolean              not null,
    sort_order    integer              not null,
    updated_at    timestamp(6)         not null,
    updated_by    uuid,
    conference_id uuid                 not null
        constraint fk5srdxdhk89gfsuteeqgudwos4
            references public.conferences,
    visible       boolean default true not null,
    constraint uk_delegate_attr_config_conference_key
        unique (conference_id, attr_key)
);

alter table public.delegate_attr_configs
    owner to asya;

create table public.delegate_attr_records
(
    id            uuid         not null
        primary key,
    created_at    timestamp(6) not null,
    created_by    uuid,
    updated_at    timestamp(6) not null,
    updated_by    uuid,
    conference_id uuid         not null
        constraint fkfguajkwvuijfle7h1s89gupqa
            references public.conferences,
    delegate_id   uuid         not null
        constraint fk8nnm2lj2j6v9wb87iwwch70mt
            references public.users
);

alter table public.delegate_attr_records
    owner to asya;

create table public.delegate_attr_values
(
    id             uuid not null
        primary key,
    value_number   numeric(20, 6),
    value_text     varchar(1000),
    attr_config_id uuid not null
        constraint fkdrysidubi3ixwaa9f5xsep27l
            references public.delegate_attr_configs,
    record_id      uuid not null
        constraint fkb21uco395w18tkt778rq4ui0o
            references public.delegate_attr_records,
    constraint uk_delegate_attr_value_record_config
        unique (record_id, attr_config_id)
);

alter table public.delegate_attr_values
    owner to asya;
