/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Asya Backend API
 * API documentation for Asya Backend application
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ConferenceAssignRequest,
  ConferenceRequest,
} from "../asyaBackendAPI.schemas";

import { customInstance } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 查看当前用户关联会议信息
 */
export type getMineResponse200 = {
  data: Blob;
  status: 200;
};

export type getMineResponseSuccess = getMineResponse200 & {
  headers: Headers;
};
export type getMineResponse = getMineResponseSuccess;

export const getGetMineUrl = () => {
  return `/api/conference`;
};

export const getMine = async (
  options?: RequestInit,
): Promise<getMineResponse> => {
  return customInstance<getMineResponse>(getGetMineUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMineQueryKey = () => {
  return [`/api/conference`] as const;
};

export const getGetMineQueryOptions = <
  TData = Awaited<ReturnType<typeof getMine>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getMine>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMineQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMine>>> = ({
    signal,
  }) => getMine({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMine>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMineQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMine>>
>;
export type GetMineQueryError = unknown;

export function useGetMine<
  TData = Awaited<ReturnType<typeof getMine>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMine>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMine>>,
          TError,
          Awaited<ReturnType<typeof getMine>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMine<
  TData = Awaited<ReturnType<typeof getMine>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMine>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMine>>,
          TError,
          Awaited<ReturnType<typeof getMine>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMine<
  TData = Awaited<ReturnType<typeof getMine>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMine>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查看当前用户关联会议信息
 */

export function useGetMine<
  TData = Awaited<ReturnType<typeof getMine>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMine>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMineQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * DH、DM、SYS_ADMIN 可更新当前关联会议
 * @summary 更新会议信息
 */
export type updateResponse200 = {
  data: Blob;
  status: 200;
};

export type updateResponseSuccess = updateResponse200 & {
  headers: Headers;
};
export type updateResponse = updateResponseSuccess;

export const getUpdateUrl = () => {
  return `/api/conference`;
};

export const update = async (
  conferenceRequest: ConferenceRequest,
  options?: RequestInit,
): Promise<updateResponse> => {
  return customInstance<updateResponse>(getUpdateUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(conferenceRequest),
  });
};

export const getUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof update>>,
    TError,
    { data: ConferenceRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof update>>,
  TError,
  { data: ConferenceRequest },
  TContext
> => {
  const mutationKey = ["update"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof update>>,
    { data: ConferenceRequest }
  > = (props) => {
    const { data } = props ?? {};

    return update(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof update>>
>;
export type UpdateMutationBody = ConferenceRequest;
export type UpdateMutationError = unknown;

/**
 * @summary 更新会议信息
 */
export const useUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof update>>,
      TError,
      { data: ConferenceRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof update>>,
  TError,
  { data: ConferenceRequest },
  TContext
> => {
  return useMutation(getUpdateMutationOptions(options), queryClient);
};
/**
 * 仅 SYS_ADMIN 可创建会议
 * @summary 新建会议
 */
export type createResponse200 = {
  data: Blob;
  status: 200;
};

export type createResponseSuccess = createResponse200 & {
  headers: Headers;
};
export type createResponse = createResponseSuccess;

export const getCreateUrl = () => {
  return `/api/conference`;
};

export const create = async (
  conferenceRequest: ConferenceRequest,
  options?: RequestInit,
): Promise<createResponse> => {
  return customInstance<createResponse>(getCreateUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(conferenceRequest),
  });
};

export const getCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof create>>,
    TError,
    { data: ConferenceRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof create>>,
  TError,
  { data: ConferenceRequest },
  TContext
> => {
  const mutationKey = ["create"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof create>>,
    { data: ConferenceRequest }
  > = (props) => {
    const { data } = props ?? {};

    return create(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof create>>
>;
export type CreateMutationBody = ConferenceRequest;
export type CreateMutationError = unknown;

/**
 * @summary 新建会议
 */
export const useCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof create>>,
      TError,
      { data: ConferenceRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof create>>,
  TError,
  { data: ConferenceRequest },
  TContext
> => {
  return useMutation(getCreateMutationOptions(options), queryClient);
};
/**
 * 仅 SYS_ADMIN 可用
 * @summary 将用户关联到会议
 */
export type assignUserResponse200 = {
  data: Blob;
  status: 200;
};

export type assignUserResponseSuccess = assignUserResponse200 & {
  headers: Headers;
};
export type assignUserResponse = assignUserResponseSuccess;

export const getAssignUserUrl = () => {
  return `/api/conference/assign`;
};

export const assignUser = async (
  conferenceAssignRequest: ConferenceAssignRequest,
  options?: RequestInit,
): Promise<assignUserResponse> => {
  return customInstance<assignUserResponse>(getAssignUserUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(conferenceAssignRequest),
  });
};

export const getAssignUserMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assignUser>>,
    TError,
    { data: ConferenceAssignRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof assignUser>>,
  TError,
  { data: ConferenceAssignRequest },
  TContext
> => {
  const mutationKey = ["assignUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof assignUser>>,
    { data: ConferenceAssignRequest }
  > = (props) => {
    const { data } = props ?? {};

    return assignUser(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AssignUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof assignUser>>
>;
export type AssignUserMutationBody = ConferenceAssignRequest;
export type AssignUserMutationError = unknown;

/**
 * @summary 将用户关联到会议
 */
export const useAssignUser = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof assignUser>>,
      TError,
      { data: ConferenceAssignRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof assignUser>>,
  TError,
  { data: ConferenceAssignRequest },
  TContext
> => {
  return useMutation(getAssignUserMutationOptions(options), queryClient);
};
/**
 * @summary 查看当前会议关联所有用户
 */
export type getUsersResponse200 = {
  data: Blob;
  status: 200;
};

export type getUsersResponseSuccess = getUsersResponse200 & {
  headers: Headers;
};
export type getUsersResponse = getUsersResponseSuccess;

export const getGetUsersUrl = () => {
  return `/api/conference/users`;
};

export const getUsers = async (
  options?: RequestInit,
): Promise<getUsersResponse> => {
  return customInstance<getUsersResponse>(getGetUsersUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetUsersQueryKey = () => {
  return [`/api/conference/users`] as const;
};

export const getGetUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUsersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsers>>> = ({
    signal,
  }) => getUsers({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUsers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsers>>
>;
export type GetUsersQueryError = unknown;

export function useGetUsers<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsers<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsers<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查看当前会议关联所有用户
 */

export function useGetUsers<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUsersQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 仅 SYS_ADMIN 可用
 * @summary 列出所有会议
 */
export type listAll1Response200 = {
  data: Blob;
  status: 200;
};

export type listAll1ResponseSuccess = listAll1Response200 & {
  headers: Headers;
};
export type listAll1Response = listAll1ResponseSuccess;

export const getListAll1Url = () => {
  return `/api/conference/all`;
};

export const listAll1 = async (
  options?: RequestInit,
): Promise<listAll1Response> => {
  return customInstance<listAll1Response>(getListAll1Url(), {
    ...options,
    method: "GET",
  });
};

export const getListAll1QueryKey = () => {
  return [`/api/conference/all`] as const;
};

export const getListAll1QueryOptions = <
  TData = Awaited<ReturnType<typeof listAll1>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listAll1>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListAll1QueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listAll1>>> = ({
    signal,
  }) => listAll1({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAll1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListAll1QueryResult = NonNullable<
  Awaited<ReturnType<typeof listAll1>>
>;
export type ListAll1QueryError = unknown;

export function useListAll1<
  TData = Awaited<ReturnType<typeof listAll1>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAll1>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAll1>>,
          TError,
          Awaited<ReturnType<typeof listAll1>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAll1<
  TData = Awaited<ReturnType<typeof listAll1>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAll1>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAll1>>,
          TError,
          Awaited<ReturnType<typeof listAll1>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAll1<
  TData = Awaited<ReturnType<typeof listAll1>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAll1>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 列出所有会议
 */

export function useListAll1<
  TData = Awaited<ReturnType<typeof listAll1>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAll1>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListAll1QueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
