/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Asya Backend API
 * API documentation for Asya Backend application
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ResetPasswordBody,
  SetRegistrationSwitchParams,
  UserRegistrationRequest,
  UserUpdateRequest,
} from "../asyaBackendAPI.schemas";

import { customInstance } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 管理员可修改所有用户；普通用户仅能修改自己的信息
 * @summary 更新用户信息
 */
export type updateUserResponse200 = {
  data: Blob;
  status: 200;
};

export type updateUserResponseSuccess = updateUserResponse200 & {
  headers: Headers;
};
export type updateUserResponse = updateUserResponseSuccess;

export const getUpdateUserUrl = (uuid: string) => {
  return `/api/users/user/${uuid}`;
};

export const updateUser = async (
  uuid: string,
  userUpdateRequest: UserUpdateRequest,
  options?: RequestInit,
): Promise<updateUserResponse> => {
  return customInstance<updateUserResponse>(getUpdateUserUrl(uuid), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userUpdateRequest),
  });
};

export const getUpdateUserMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUser>>,
    TError,
    { uuid: string; data: UserUpdateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUser>>,
  TError,
  { uuid: string; data: UserUpdateRequest },
  TContext
> => {
  const mutationKey = ["updateUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUser>>,
    { uuid: string; data: UserUpdateRequest }
  > = (props) => {
    const { uuid, data } = props ?? {};

    return updateUser(uuid, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUser>>
>;
export type UpdateUserMutationBody = UserUpdateRequest;
export type UpdateUserMutationError = unknown;

/**
 * @summary 更新用户信息
 */
export const useUpdateUser = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUser>>,
      TError,
      { uuid: string; data: UserUpdateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateUser>>,
  TError,
  { uuid: string; data: UserUpdateRequest },
  TContext
> => {
  return useMutation(getUpdateUserMutationOptions(options), queryClient);
};
/**
 * 仅系统管理员可执行
 * @summary 管理员重置用户密码
 */
export type resetPasswordResponse200 = {
  data: Blob;
  status: 200;
};

export type resetPasswordResponseSuccess = resetPasswordResponse200 & {
  headers: Headers;
};
export type resetPasswordResponse = resetPasswordResponseSuccess;

export const getResetPasswordUrl = (uuid: string) => {
  return `/api/users/${uuid}/password-reset`;
};

export const resetPassword = async (
  uuid: string,
  resetPasswordBody: ResetPasswordBody,
  options?: RequestInit,
): Promise<resetPasswordResponse> => {
  return customInstance<resetPasswordResponse>(getResetPasswordUrl(uuid), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(resetPasswordBody),
  });
};

export const getResetPasswordMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resetPassword>>,
    TError,
    { uuid: string; data: ResetPasswordBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof resetPassword>>,
  TError,
  { uuid: string; data: ResetPasswordBody },
  TContext
> => {
  const mutationKey = ["resetPassword"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof resetPassword>>,
    { uuid: string; data: ResetPasswordBody }
  > = (props) => {
    const { uuid, data } = props ?? {};

    return resetPassword(uuid, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ResetPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof resetPassword>>
>;
export type ResetPasswordMutationBody = ResetPasswordBody;
export type ResetPasswordMutationError = unknown;

/**
 * @summary 管理员重置用户密码
 */
export const useResetPassword = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof resetPassword>>,
      TError,
      { uuid: string; data: ResetPasswordBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof resetPassword>>,
  TError,
  { uuid: string; data: ResetPasswordBody },
  TContext
> => {
  return useMutation(getResetPasswordMutationOptions(options), queryClient);
};
/**
 * @summary 查询当前是否允许注册
 */
export type getRegistrationSwitchResponse200 = {
  data: Blob;
  status: 200;
};

export type getRegistrationSwitchResponseSuccess =
  getRegistrationSwitchResponse200 & {
    headers: Headers;
  };
export type getRegistrationSwitchResponse =
  getRegistrationSwitchResponseSuccess;

export const getGetRegistrationSwitchUrl = () => {
  return `/api/users/registration-switch`;
};

export const getRegistrationSwitch = async (
  options?: RequestInit,
): Promise<getRegistrationSwitchResponse> => {
  return customInstance<getRegistrationSwitchResponse>(
    getGetRegistrationSwitchUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetRegistrationSwitchQueryKey = () => {
  return [`/api/users/registration-switch`] as const;
};

export const getGetRegistrationSwitchQueryOptions = <
  TData = Awaited<ReturnType<typeof getRegistrationSwitch>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getRegistrationSwitch>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRegistrationSwitchQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getRegistrationSwitch>>
  > = ({ signal }) => getRegistrationSwitch({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRegistrationSwitch>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRegistrationSwitchQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRegistrationSwitch>>
>;
export type GetRegistrationSwitchQueryError = unknown;

export function useGetRegistrationSwitch<
  TData = Awaited<ReturnType<typeof getRegistrationSwitch>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRegistrationSwitch>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRegistrationSwitch>>,
          TError,
          Awaited<ReturnType<typeof getRegistrationSwitch>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRegistrationSwitch<
  TData = Awaited<ReturnType<typeof getRegistrationSwitch>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRegistrationSwitch>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRegistrationSwitch>>,
          TError,
          Awaited<ReturnType<typeof getRegistrationSwitch>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRegistrationSwitch<
  TData = Awaited<ReturnType<typeof getRegistrationSwitch>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRegistrationSwitch>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询当前是否允许注册
 */

export function useGetRegistrationSwitch<
  TData = Awaited<ReturnType<typeof getRegistrationSwitch>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRegistrationSwitch>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetRegistrationSwitchQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 仅系统管理员可执行。true: 允许, false: 禁止
 * @summary 设置是否允许注册
 */
export type setRegistrationSwitchResponse200 = {
  data: Blob;
  status: 200;
};

export type setRegistrationSwitchResponseSuccess =
  setRegistrationSwitchResponse200 & {
    headers: Headers;
  };
export type setRegistrationSwitchResponse =
  setRegistrationSwitchResponseSuccess;

export const getSetRegistrationSwitchUrl = (
  params: SetRegistrationSwitchParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/users/registration-switch?${stringifiedParams}`
    : `/api/users/registration-switch`;
};

export const setRegistrationSwitch = async (
  params: SetRegistrationSwitchParams,
  options?: RequestInit,
): Promise<setRegistrationSwitchResponse> => {
  return customInstance<setRegistrationSwitchResponse>(
    getSetRegistrationSwitchUrl(params),
    {
      ...options,
      method: "POST",
    },
  );
};

export const getSetRegistrationSwitchMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof setRegistrationSwitch>>,
    TError,
    { params: SetRegistrationSwitchParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof setRegistrationSwitch>>,
  TError,
  { params: SetRegistrationSwitchParams },
  TContext
> => {
  const mutationKey = ["setRegistrationSwitch"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof setRegistrationSwitch>>,
    { params: SetRegistrationSwitchParams }
  > = (props) => {
    const { params } = props ?? {};

    return setRegistrationSwitch(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SetRegistrationSwitchMutationResult = NonNullable<
  Awaited<ReturnType<typeof setRegistrationSwitch>>
>;

export type SetRegistrationSwitchMutationError = unknown;

/**
 * @summary 设置是否允许注册
 */
export const useSetRegistrationSwitch = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof setRegistrationSwitch>>,
      TError,
      { params: SetRegistrationSwitchParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof setRegistrationSwitch>>,
  TError,
  { params: SetRegistrationSwitchParams },
  TContext
> => {
  return useMutation(
    getSetRegistrationSwitchMutationOptions(options),
    queryClient,
  );
};
/**
 * 创建新用户。密码会使用 BCrypt 进行加密后存储。
 * @summary 用户注册
 */
export type registerResponse200 = {
  data: Blob;
  status: 200;
};

export type registerResponseSuccess = registerResponse200 & {
  headers: Headers;
};
export type registerResponse = registerResponseSuccess;

export const getRegisterUrl = () => {
  return `/api/users/register`;
};

export const register = async (
  userRegistrationRequest: UserRegistrationRequest,
  options?: RequestInit,
): Promise<registerResponse> => {
  return customInstance<registerResponse>(getRegisterUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userRegistrationRequest),
  });
};

export const getRegisterMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof register>>,
    TError,
    { data: UserRegistrationRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof register>>,
  TError,
  { data: UserRegistrationRequest },
  TContext
> => {
  const mutationKey = ["register"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof register>>,
    { data: UserRegistrationRequest }
  > = (props) => {
    const { data } = props ?? {};

    return register(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof register>>
>;
export type RegisterMutationBody = UserRegistrationRequest;
export type RegisterMutationError = unknown;

/**
 * @summary 用户注册
 */
export const useRegister = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof register>>,
      TError,
      { data: UserRegistrationRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof register>>,
  TError,
  { data: UserRegistrationRequest },
  TContext
> => {
  return useMutation(getRegisterMutationOptions(options), queryClient);
};
export type loginResponse200 = {
  data: Blob;
  status: 200;
};

export type loginResponseSuccess = loginResponse200 & {
  headers: Headers;
};
export type loginResponse = loginResponseSuccess;

export const getLoginUrl = () => {
  return `/api/users/login`;
};

export const login = async (
  userRegistrationRequest: UserRegistrationRequest,
  options?: RequestInit,
): Promise<loginResponse> => {
  return customInstance<loginResponse>(getLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userRegistrationRequest),
  });
};

export const getLoginMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: UserRegistrationRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: UserRegistrationRequest },
  TContext
> => {
  const mutationKey = ["login"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof login>>,
    { data: UserRegistrationRequest }
  > = (props) => {
    const { data } = props ?? {};

    return login(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof login>>
>;
export type LoginMutationBody = UserRegistrationRequest;
export type LoginMutationError = unknown;

export const useLogin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof login>>,
      TError,
      { data: UserRegistrationRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: UserRegistrationRequest },
  TContext
> => {
  return useMutation(getLoginMutationOptions(options), queryClient);
};
/**
 * 仅系统管理员可访问
 * @summary 获取所有用户
 */
export type listAllResponse200 = {
  data: Blob;
  status: 200;
};

export type listAllResponseSuccess = listAllResponse200 & {
  headers: Headers;
};
export type listAllResponse = listAllResponseSuccess;

export const getListAllUrl = () => {
  return `/api/users`;
};

export const listAll = async (
  options?: RequestInit,
): Promise<listAllResponse> => {
  return customInstance<listAllResponse>(getListAllUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListAllQueryKey = () => {
  return [`/api/users`] as const;
};

export const getListAllQueryOptions = <
  TData = Awaited<ReturnType<typeof listAll>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listAll>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listAll>>> = ({
    signal,
  }) => listAll({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAll>>
>;
export type ListAllQueryError = unknown;

export function useListAll<
  TData = Awaited<ReturnType<typeof listAll>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAll>>,
          TError,
          Awaited<ReturnType<typeof listAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAll<
  TData = Awaited<ReturnType<typeof listAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAll>>,
          TError,
          Awaited<ReturnType<typeof listAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAll<
  TData = Awaited<ReturnType<typeof listAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 获取所有用户
 */

export function useListAll<
  TData = Awaited<ReturnType<typeof listAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary 获取当前登录用户信息
 */
export type getCurrentUserResponse200 = {
  data: Blob;
  status: 200;
};

export type getCurrentUserResponseSuccess = getCurrentUserResponse200 & {
  headers: Headers;
};
export type getCurrentUserResponse = getCurrentUserResponseSuccess;

export const getGetCurrentUserUrl = () => {
  return `/api/users/user`;
};

export const getCurrentUser = async (
  options?: RequestInit,
): Promise<getCurrentUserResponse> => {
  return customInstance<getCurrentUserResponse>(getGetCurrentUserUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetCurrentUserQueryKey = () => {
  return [`/api/users/user`] as const;
};

export const getGetCurrentUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrentUserQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({
    signal,
  }) => getCurrentUser({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUser>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCurrentUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUser>>
>;
export type GetCurrentUserQueryError = unknown;

export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 获取当前登录用户信息
 */

export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCurrentUserQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 仅系统管理员可执行
 * @summary 删除用户
 */
export type deleteUserResponse200 = {
  data: Blob;
  status: 200;
};

export type deleteUserResponseSuccess = deleteUserResponse200 & {
  headers: Headers;
};
export type deleteUserResponse = deleteUserResponseSuccess;

export const getDeleteUserUrl = (uuid: string) => {
  return `/api/users/${uuid}`;
};

export const deleteUser = async (
  uuid: string,
  options?: RequestInit,
): Promise<deleteUserResponse> => {
  return customInstance<deleteUserResponse>(getDeleteUserUrl(uuid), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteUserMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteUser>>,
    TError,
    { uuid: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteUser>>,
  TError,
  { uuid: string },
  TContext
> => {
  const mutationKey = ["deleteUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteUser>>,
    { uuid: string }
  > = (props) => {
    const { uuid } = props ?? {};

    return deleteUser(uuid, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUser>>
>;

export type DeleteUserMutationError = unknown;

/**
 * @summary 删除用户
 */
export const useDeleteUser = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteUser>>,
      TError,
      { uuid: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteUser>>,
  TError,
  { uuid: string },
  TContext
> => {
  return useMutation(getDeleteUserMutationOptions(options), queryClient);
};
