/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Asya Backend API
 * API documentation for Asya Backend application
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  RoundPublishRequest,
  RoundSetCurrentRequest,
  RoundSetNextRequest,
  RoundSetRemainingRequest,
  RoundUpdateRequest,
} from "../asyaBackendAPI.schemas";

import { customInstance } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 所有登录用户可查询自己所在会议下的回合详情
 * @summary 按ID查询回合详情
 */
export type detailResponse200 = {
  data: Blob;
  status: 200;
};

export type detailResponseSuccess = detailResponse200 & {
  headers: Headers;
};
export type detailResponse = detailResponseSuccess;

export const getDetailUrl = (roundId: string) => {
  return `/api/round/${roundId}`;
};

export const detail = async (
  roundId: string,
  options?: RequestInit,
): Promise<detailResponse> => {
  return customInstance<detailResponse>(getDetailUrl(roundId), {
    ...options,
    method: "GET",
  });
};

export const getDetailQueryKey = (roundId: string) => {
  return [`/api/round/${roundId}`] as const;
};

export const getDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof detail>>,
  TError = unknown,
>(
  roundId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDetailQueryKey(roundId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof detail>>> = ({
    signal,
  }) => detail(roundId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!roundId,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof detail>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type DetailQueryResult = NonNullable<Awaited<ReturnType<typeof detail>>>;
export type DetailQueryError = unknown;

export function useDetail<
  TData = Awaited<ReturnType<typeof detail>>,
  TError = unknown,
>(
  roundId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof detail>>,
          TError,
          Awaited<ReturnType<typeof detail>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDetail<
  TData = Awaited<ReturnType<typeof detail>>,
  TError = unknown,
>(
  roundId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof detail>>,
          TError,
          Awaited<ReturnType<typeof detail>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDetail<
  TData = Awaited<ReturnType<typeof detail>>,
  TError = unknown,
>(
  roundId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 按ID查询回合详情
 */

export function useDetail<
  TData = Awaited<ReturnType<typeof detail>>,
  TError = unknown,
>(
  roundId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDetailQueryOptions(roundId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * DH、DM、SYS_ADMIN 可修改回合名称和总时间
 * @summary 修改指定回合
 */
export type updateResponse200 = {
  data: Blob;
  status: 200;
};

export type updateResponseSuccess = updateResponse200 & {
  headers: Headers;
};
export type updateResponse = updateResponseSuccess;

export const getUpdateUrl = (roundId: string) => {
  return `/api/round/${roundId}`;
};

export const update = async (
  roundId: string,
  roundUpdateRequest: RoundUpdateRequest,
  options?: RequestInit,
): Promise<updateResponse> => {
  return customInstance<updateResponse>(getUpdateUrl(roundId), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(roundUpdateRequest),
  });
};

export const getUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof update>>,
    TError,
    { roundId: string; data: RoundUpdateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof update>>,
  TError,
  { roundId: string; data: RoundUpdateRequest },
  TContext
> => {
  const mutationKey = ["update"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof update>>,
    { roundId: string; data: RoundUpdateRequest }
  > = (props) => {
    const { roundId, data } = props ?? {};

    return update(roundId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof update>>
>;
export type UpdateMutationBody = RoundUpdateRequest;
export type UpdateMutationError = unknown;

/**
 * @summary 修改指定回合
 */
export const useUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof update>>,
      TError,
      { roundId: string; data: RoundUpdateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof update>>,
  TError,
  { roundId: string; data: RoundUpdateRequest },
  TContext
> => {
  return useMutation(getUpdateMutationOptions(options), queryClient);
};
/**
 * DH、DM、SYS_ADMIN 可修改回合剩余时间（秒）
 * @summary 设置回合剩余时间
 */
export type updateRemainingResponse200 = {
  data: Blob;
  status: 200;
};

export type updateRemainingResponseSuccess = updateRemainingResponse200 & {
  headers: Headers;
};
export type updateRemainingResponse = updateRemainingResponseSuccess;

export const getUpdateRemainingUrl = (roundId: string) => {
  return `/api/round/${roundId}/remaining`;
};

export const updateRemaining = async (
  roundId: string,
  roundSetRemainingRequest: RoundSetRemainingRequest,
  options?: RequestInit,
): Promise<updateRemainingResponse> => {
  return customInstance<updateRemainingResponse>(
    getUpdateRemainingUrl(roundId),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(roundSetRemainingRequest),
    },
  );
};

export const getUpdateRemainingMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateRemaining>>,
    TError,
    { roundId: string; data: RoundSetRemainingRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateRemaining>>,
  TError,
  { roundId: string; data: RoundSetRemainingRequest },
  TContext
> => {
  const mutationKey = ["updateRemaining"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateRemaining>>,
    { roundId: string; data: RoundSetRemainingRequest }
  > = (props) => {
    const { roundId, data } = props ?? {};

    return updateRemaining(roundId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateRemainingMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateRemaining>>
>;
export type UpdateRemainingMutationBody = RoundSetRemainingRequest;
export type UpdateRemainingMutationError = unknown;

/**
 * @summary 设置回合剩余时间
 */
export const useUpdateRemaining = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateRemaining>>,
      TError,
      { roundId: string; data: RoundSetRemainingRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateRemaining>>,
  TError,
  { roundId: string; data: RoundSetRemainingRequest },
  TContext
> => {
  return useMutation(getUpdateRemainingMutationOptions(options), queryClient);
};
/**
 * DH、DM、SYS_ADMIN 可设置某个 round 的 nextRoundId（可清空）
 * @summary 设置下一回合
 */
export type setNextResponse200 = {
  data: Blob;
  status: 200;
};

export type setNextResponseSuccess = setNextResponse200 & {
  headers: Headers;
};
export type setNextResponse = setNextResponseSuccess;

export const getSetNextUrl = (roundId: string) => {
  return `/api/round/${roundId}/next`;
};

export const setNext = async (
  roundId: string,
  roundSetNextRequest: RoundSetNextRequest,
  options?: RequestInit,
): Promise<setNextResponse> => {
  return customInstance<setNextResponse>(getSetNextUrl(roundId), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(roundSetNextRequest),
  });
};

export const getSetNextMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof setNext>>,
    TError,
    { roundId: string; data: RoundSetNextRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof setNext>>,
  TError,
  { roundId: string; data: RoundSetNextRequest },
  TContext
> => {
  const mutationKey = ["setNext"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof setNext>>,
    { roundId: string; data: RoundSetNextRequest }
  > = (props) => {
    const { roundId, data } = props ?? {};

    return setNext(roundId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SetNextMutationResult = NonNullable<
  Awaited<ReturnType<typeof setNext>>
>;
export type SetNextMutationBody = RoundSetNextRequest;
export type SetNextMutationError = unknown;

/**
 * @summary 设置下一回合
 */
export const useSetNext = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof setNext>>,
      TError,
      { roundId: string; data: RoundSetNextRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof setNext>>,
  TError,
  { roundId: string; data: RoundSetNextRequest },
  TContext
> => {
  return useMutation(getSetNextMutationOptions(options), queryClient);
};
/**
 * 所有登录用户可查看当前回合与剩余时间
 * @summary 查询当前回合状态
 */
export type currentResponse200 = {
  data: Blob;
  status: 200;
};

export type currentResponseSuccess = currentResponse200 & {
  headers: Headers;
};
export type currentResponse = currentResponseSuccess;

export const getCurrentUrl = () => {
  return `/api/round/current`;
};

export const current = async (
  options?: RequestInit,
): Promise<currentResponse> => {
  return customInstance<currentResponse>(getCurrentUrl(), {
    ...options,
    method: "GET",
  });
};

export const getCurrentQueryKey = () => {
  return [`/api/round/current`] as const;
};

export const getCurrentQueryOptions = <
  TData = Awaited<ReturnType<typeof current>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof current>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCurrentQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof current>>> = ({
    signal,
  }) => current({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof current>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CurrentQueryResult = NonNullable<
  Awaited<ReturnType<typeof current>>
>;
export type CurrentQueryError = unknown;

export function useCurrent<
  TData = Awaited<ReturnType<typeof current>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof current>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof current>>,
          TError,
          Awaited<ReturnType<typeof current>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCurrent<
  TData = Awaited<ReturnType<typeof current>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof current>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof current>>,
          TError,
          Awaited<ReturnType<typeof current>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCurrent<
  TData = Awaited<ReturnType<typeof current>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof current>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询当前回合状态
 */

export function useCurrent<
  TData = Awaited<ReturnType<typeof current>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof current>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCurrentQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * DH、DM、SYS_ADMIN 可将当前回合切换为已有回合
 * @summary 设置当前回合
 */
export type updateCurrentResponse200 = {
  data: Blob;
  status: 200;
};

export type updateCurrentResponseSuccess = updateCurrentResponse200 & {
  headers: Headers;
};
export type updateCurrentResponse = updateCurrentResponseSuccess;

export const getUpdateCurrentUrl = () => {
  return `/api/round/current`;
};

export const updateCurrent = async (
  roundSetCurrentRequest: RoundSetCurrentRequest,
  options?: RequestInit,
): Promise<updateCurrentResponse> => {
  return customInstance<updateCurrentResponse>(getUpdateCurrentUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(roundSetCurrentRequest),
  });
};

export const getUpdateCurrentMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCurrent>>,
    TError,
    { data: RoundSetCurrentRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCurrent>>,
  TError,
  { data: RoundSetCurrentRequest },
  TContext
> => {
  const mutationKey = ["updateCurrent"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCurrent>>,
    { data: RoundSetCurrentRequest }
  > = (props) => {
    const { data } = props ?? {};

    return updateCurrent(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCurrentMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCurrent>>
>;
export type UpdateCurrentMutationBody = RoundSetCurrentRequest;
export type UpdateCurrentMutationError = unknown;

/**
 * @summary 设置当前回合
 */
export const useUpdateCurrent = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCurrent>>,
      TError,
      { data: RoundSetCurrentRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateCurrent>>,
  TError,
  { data: RoundSetCurrentRequest },
  TContext
> => {
  return useMutation(getUpdateCurrentMutationOptions(options), queryClient);
};
/**
 * DH、DM、SYS_ADMIN 可查看
 * @summary 列出本会议所有回合
 */
export type listResponse200 = {
  data: Blob;
  status: 200;
};

export type listResponseSuccess = listResponse200 & {
  headers: Headers;
};
export type listResponse = listResponseSuccess;

export const getListUrl = () => {
  return `/api/round`;
};

export const list = async (options?: RequestInit): Promise<listResponse> => {
  return customInstance<listResponse>(getListUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListQueryKey = () => {
  return [`/api/round`] as const;
};

export const getListQueryOptions = <
  TData = Awaited<ReturnType<typeof list>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof list>>> = ({
    signal,
  }) => list({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof list>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListQueryResult = NonNullable<Awaited<ReturnType<typeof list>>>;
export type ListQueryError = unknown;

export function useList<
  TData = Awaited<ReturnType<typeof list>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof list>>,
          TError,
          Awaited<ReturnType<typeof list>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useList<
  TData = Awaited<ReturnType<typeof list>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof list>>,
          TError,
          Awaited<ReturnType<typeof list>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useList<
  TData = Awaited<ReturnType<typeof list>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 列出本会议所有回合
 */

export function useList<
  TData = Awaited<ReturnType<typeof list>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * DH、DM、SYS_ADMIN 可发布回合，发布后立即切换为当前回合
 * @summary 发布回合
 */
export type publishResponse200 = {
  data: Blob;
  status: 200;
};

export type publishResponseSuccess = publishResponse200 & {
  headers: Headers;
};
export type publishResponse = publishResponseSuccess;

export const getPublishUrl = () => {
  return `/api/round`;
};

export const publish = async (
  roundPublishRequest: RoundPublishRequest,
  options?: RequestInit,
): Promise<publishResponse> => {
  return customInstance<publishResponse>(getPublishUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(roundPublishRequest),
  });
};

export const getPublishMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof publish>>,
    TError,
    { data: RoundPublishRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof publish>>,
  TError,
  { data: RoundPublishRequest },
  TContext
> => {
  const mutationKey = ["publish"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof publish>>,
    { data: RoundPublishRequest }
  > = (props) => {
    const { data } = props ?? {};

    return publish(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PublishMutationResult = NonNullable<
  Awaited<ReturnType<typeof publish>>
>;
export type PublishMutationBody = RoundPublishRequest;
export type PublishMutationError = unknown;

/**
 * @summary 发布回合
 */
export const usePublish = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof publish>>,
      TError,
      { data: RoundPublishRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof publish>>,
  TError,
  { data: RoundPublishRequest },
  TContext
> => {
  return useMutation(getPublishMutationOptions(options), queryClient);
};
/**
 * DH、DM、SYS_ADMIN 可恢复当前回合
 * @summary 恢复当前回合
 */
export type resumeResponse200 = {
  data: Blob;
  status: 200;
};

export type resumeResponseSuccess = resumeResponse200 & {
  headers: Headers;
};
export type resumeResponse = resumeResponseSuccess;

export const getResumeUrl = (roundId: string) => {
  return `/api/round/${roundId}/resume`;
};

export const resume = async (
  roundId: string,
  options?: RequestInit,
): Promise<resumeResponse> => {
  return customInstance<resumeResponse>(getResumeUrl(roundId), {
    ...options,
    method: "POST",
  });
};

export const getResumeMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resume>>,
    TError,
    { roundId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof resume>>,
  TError,
  { roundId: string },
  TContext
> => {
  const mutationKey = ["resume"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof resume>>,
    { roundId: string }
  > = (props) => {
    const { roundId } = props ?? {};

    return resume(roundId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ResumeMutationResult = NonNullable<
  Awaited<ReturnType<typeof resume>>
>;

export type ResumeMutationError = unknown;

/**
 * @summary 恢复当前回合
 */
export const useResume = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof resume>>,
      TError,
      { roundId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof resume>>,
  TError,
  { roundId: string },
  TContext
> => {
  return useMutation(getResumeMutationOptions(options), queryClient);
};
/**
 * DH、DM、SYS_ADMIN 可暂停当前回合
 * @summary 暂停当前回合
 */
export type pauseResponse200 = {
  data: Blob;
  status: 200;
};

export type pauseResponseSuccess = pauseResponse200 & {
  headers: Headers;
};
export type pauseResponse = pauseResponseSuccess;

export const getPauseUrl = (roundId: string) => {
  return `/api/round/${roundId}/pause`;
};

export const pause = async (
  roundId: string,
  options?: RequestInit,
): Promise<pauseResponse> => {
  return customInstance<pauseResponse>(getPauseUrl(roundId), {
    ...options,
    method: "POST",
  });
};

export const getPauseMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pause>>,
    TError,
    { roundId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof pause>>,
  TError,
  { roundId: string },
  TContext
> => {
  const mutationKey = ["pause"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pause>>,
    { roundId: string }
  > = (props) => {
    const { roundId } = props ?? {};

    return pause(roundId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PauseMutationResult = NonNullable<
  Awaited<ReturnType<typeof pause>>
>;

export type PauseMutationError = unknown;

/**
 * @summary 暂停当前回合
 */
export const usePause = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pause>>,
      TError,
      { roundId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof pause>>,
  TError,
  { roundId: string },
  TContext
> => {
  return useMutation(getPauseMutationOptions(options), queryClient);
};
