// <auto-generated />
using System;
using AsyaMun.Api.Data;
using AsyaMun.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AsyaMun.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "attachmenttargettype", new[] { "ANNOUNCEMENT", "DIRECTIVE", "MESSAGE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "auditactiontype", new[] { "ANNOUNCEMENT_IMAGE_UPDATE", "ATTACHMENT_DELETE", "ATTACHMENT_UPLOAD", "CONFERENCE_ASSIGN_USER", "CONFERENCE_CREATE", "CONFERENCE_UPDATE", "DELEGATE_ATTR_CONFIG_CREATE", "DELEGATE_ATTR_CONFIG_UPDATE", "DELEGATE_ATTR_RECORD_CREATE", "DELEGATE_ATTR_RECORD_DELETE", "DELEGATE_ATTR_RECORD_UPDATE", "INSTRUCTION_CREATE", "INSTRUCTION_REVIEW", "INSTRUCTION_SUBMISSION_SWITCH", "MESSAGE_CREATE", "MESSAGE_DELETE", "MESSAGE_UPDATE", "ROUND_AUTO_ADVANCE", "ROUND_PAUSE", "ROUND_PUBLISH", "ROUND_RESUME", "ROUND_SET_CURRENT", "ROUND_SET_NEXT", "ROUND_SET_REMAINING", "ROUND_UPDATE", "TEST_DATA_BOOTSTRAP", "TIMELINE_JUMP", "TIMELINE_UPDATE", "USER_BATCH_REGISTER", "USER_BATCH_REGISTER_FULL", "USER_DELETE", "USER_GROUP_CREATE", "USER_GROUP_DELETE", "USER_GROUP_MEMBERS_UPDATE", "USER_GROUP_MEMBER_REMOVE", "USER_GROUP_UPDATE", "USER_LOGIN", "USER_PASSWORD_RESET", "USER_REGISTER", "USER_REGISTRATION_SWITCH", "USER_UPDATE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "conferencestatus", new[] { "COMPLETED", "PREPARING", "RUNNING" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "delegateattrtype", new[] { "NUMBER", "TEXT" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "instructionstatus", new[] { "FEEDBACKED", "IN_PROGRESS", "REJECTED", "SUBMITTED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "instructiontype", new[] { "DIPLOMACY", "ECONOMY", "INTERNAL", "MILITARY", "OTHER" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "messagetype", new[] { "AMENDMENT", "CRISIS", "DECLARATION", "EVENT", "MEMORANDUM", "NEWS", "PROTOCOL", "SECRET_LETTER", "WAR_REPORT" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "roundstatus", new[] { "PAUSED", "RUNNING" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "userrole", new[] { "DELEGATE", "DH", "DM", "SYS_ADMIN" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AsyaMun.Api.Models.Attachment", b =>
                {
                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<uint>("FileBlob")
                        .HasColumnType("oid")
                        .HasColumnName("file_blob");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("file_type");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<AttachmentTargetType?>("TargetType")
                        .HasColumnType("public.attachmenttargettype")
                        .HasColumnName("target_type");

                    b.HasKey("Uuid")
                        .HasName("attachments_pkey");

                    b.HasIndex(new[] { "MessageId" }, "idx_attachment_message_id");

                    b.HasIndex(new[] { "TargetType", "TargetId" }, "idx_attachment_target");

                    b.ToTable("attachments", null, t =>
                        {
                            t.HasCheckConstraint("chk_attachments_file_name_not_blank", "btrim(file_name) <> ''");

                            t.HasCheckConstraint("chk_attachments_file_size_non_negative", "file_size >= 0");

                            t.HasCheckConstraint("chk_attachments_file_type_not_blank", "btrim(file_type) <> ''");

                            t.HasCheckConstraint("chk_attachments_message_target_consistency", "message_id is null or (target_type = 'MESSAGE' and target_id is not null)");

                            t.HasCheckConstraint("chk_attachments_target_pair", "(target_type is null and target_id is null) or (target_type = 'ANNOUNCEMENT' and target_id is null) or (target_type is not null and target_id is not null)");
                        });
                });

            modelBuilder.Entity("AsyaMun.Api.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<AuditActionType>("ActionType")
                        .HasColumnType("public.auditactiontype")
                        .HasColumnName("action_type");

                    b.Property<string>("ActorIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("actor_ip");

                    b.Property<string>("ActorName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("actor_name");

                    b.Property<Guid?>("ActorUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_uuid");

                    b.Property<string>("ContextData")
                        .HasColumnType("text")
                        .HasColumnName("context_data");

                    b.Property<string>("EventContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_content");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("timestamp(6) without time zone")
                        .HasColumnName("event_time");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("request_method");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("request_path");

                    b.Property<string>("RequestQuery")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("request_query");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("resource_type");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("audit_logs_pkey");

                    b.HasIndex(new[] { "ActionType" }, "idx_audit_logs_action_type");

                    b.HasIndex(new[] { "ActorUuid" }, "idx_audit_logs_actor_uuid");

                    b.HasIndex(new[] { "EventTime" }, "idx_audit_logs_event_time")
                        .IsDescending();

                    b.HasIndex(new[] { "Success" }, "idx_audit_logs_success");

                    b.ToTable("audit_logs", null, t =>
                        {
                            t.HasCheckConstraint("chk_audit_logs_event_content_not_blank", "btrim(event_content) <> ''");
                        });
                });

            modelBuilder.Entity("AsyaMun.Api.Models.Conference", b =>
                {
                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<bool>("InstructionSubmissionPaused")
                        .HasColumnType("boolean")
                        .HasColumnName("instruction_submission_paused");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<ConferenceStatus>("Status")
                        .HasColumnType("public.conferencestatus")
                        .HasColumnName("status");

                    b.HasKey("Uuid")
                        .HasName("conferences_pkey");

                    b.ToTable("conferences", null, t =>
                        {
                            t.HasCheckConstraint("chk_conferences_description_not_blank", "btrim(description) <> ''");

                            t.HasCheckConstraint("chk_conferences_name_not_blank", "btrim(name) <> ''");
                        });
                });

            modelBuilder.Entity("AsyaMun.Api.Models.DelegateAttrConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttrKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("attr_key");

                    b.Property<string>("AttrLabel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("attr_label");

                    b.Property<DelegateAttrType>("AttrType")
                        .HasColumnType("public.delegateattrtype")
                        .HasColumnName("attr_type");

                    b.Property<Guid>("ConferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("conference_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(6) without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(6) without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<bool>("Visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("visible");

                    b.HasKey("Id")
                        .HasName("delegate_attr_configs_pkey");

                    b.HasIndex(new[] { "ConferenceId", "Enabled", "SortOrder", "Id" }, "idx_delegate_attr_configs_conference_enabled_sort");

                    b.HasIndex(new[] { "ConferenceId", "SortOrder", "Id" }, "idx_delegate_attr_configs_conference_sort");

                    b.HasIndex(new[] { "ConferenceId", "AttrKey" }, "uk_delegate_attr_config_conference_key")
                        .IsUnique();

                    b.ToTable("delegate_attr_configs", null, t =>
                        {
                            t.HasCheckConstraint("chk_delegate_attr_configs_key_not_blank", "btrim(attr_key) <> ''");

                            t.HasCheckConstraint("chk_delegate_attr_configs_label_not_blank", "btrim(attr_label) <> ''");
                        });
                });

            modelBuilder.Entity("AsyaMun.Api.Models.DelegateAttrRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("conference_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(6) without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DelegateId")
                        .HasColumnType("uuid")
                        .HasColumnName("delegate_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(6) without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("delegate_attr_records_pkey");

                    b.HasIndex(new[] { "ConferenceId" }, "idx_delegate_attr_records_conference");

                    b.HasIndex(new[] { "DelegateId", "ConferenceId", "CreatedAt", "Id" }, "idx_delegate_attr_records_delegate_conference")
                        .IsDescending(false, false, true, true);

                    b.ToTable("delegate_attr_records", (string)null);
                });

            modelBuilder.Entity("AsyaMun.Api.Models.DelegateAttrValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttrConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("attr_config_id");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<decimal?>("ValueNumber")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("value_number");

                    b.Property<string>("ValueText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("value_text");

                    b.HasKey("Id")
                        .HasName("delegate_attr_values_pkey");

                    b.HasIndex(new[] { "AttrConfigId" }, "idx_delegate_attr_values_attr_config");

                    b.HasIndex(new[] { "RecordId", "AttrConfigId" }, "uk_delegate_attr_value_record_config")
                        .IsUnique();

                    b.ToTable("delegate_attr_values", null, t =>
                        {
                            t.HasCheckConstraint("chk_delegate_attr_values_not_both_null", "value_text is not null or value_number is not null");

                            t.HasCheckConstraint("chk_delegate_attr_values_text_not_blank", "value_text is null or btrim(value_text) <> ''");
                        });
                });

            modelBuilder.Entity("AsyaMun.Api.Models.Instruction", b =>
                {
                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<Guid>("ConferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("conference_id");

                    b.Property<string>("InstructionContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instruction_content");

                    b.Property<InstructionType>("InstructionType")
                        .HasColumnType("public.instructiontype")
                        .HasColumnName("instruction_type");

                    b.Property<string>("ReviewComment")
                        .HasColumnType("text")
                        .HasColumnName("review_comment");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("ReviewedGameTime")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reviewed_game_time");

                    b.Property<DateTime?>("ReviewedRealTime")
                        .HasColumnType("timestamp(6) without time zone")
                        .HasColumnName("reviewed_real_time");

                    b.Property<InstructionStatus>("Status")
                        .HasColumnType("public.instructionstatus")
                        .HasColumnName("status");

                    b.Property<string>("SubmitGameTime")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("submit_game_time");

                    b.Property<DateTime>("SubmitRealTime")
                        .HasColumnType("timestamp(6) without time zone")
                        .HasColumnName("submit_real_time");

                    b.Property<Guid>("SubmitterId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitter_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Uuid")
                        .HasName("instructions_pkey");

                    b.HasIndex(new[] { "ConferenceId", "Status", "InstructionType", "SubmitRealTime", "Uuid" }, "idx_instructions_conference_query")
                        .IsDescending(false, false, false, true, true);

                    b.HasIndex(new[] { "ReviewedBy" }, "idx_instructions_reviewed_by");

                    b.HasIndex(new[] { "SubmitterId", "Status", "SubmitRealTime", "Uuid" }, "idx_instructions_submitter_status_time")
                        .IsDescending(false, false, true, true);

                    b.ToTable("instructions", null, t =>
                        {
                            t.HasCheckConstraint("chk_instructions_content_not_blank", "btrim(instruction_content) <> ''");

                            t.HasCheckConstraint("chk_instructions_review_payload", "(reviewed_by is null and reviewed_real_time is null and reviewed_game_time is null) or reviewed_by is not null");

                            t.HasCheckConstraint("chk_instructions_reviewed_game_time_not_blank", "reviewed_game_time is null or btrim(reviewed_game_time) <> ''");

                            t.HasCheckConstraint("chk_instructions_submit_game_time_not_blank", "btrim(submit_game_time) <> ''");

                            t.HasCheckConstraint("chk_instructions_title_not_blank", "btrim(title) <> ''");
                        });
                });

            modelBuilder.Entity("AsyaMun.Api.Models.Message", b =>
                {
                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Brief")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("brief");

                    b.Property<Guid>("ConferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("conference_id");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean")
                        .HasColumnName("is_secret");

                    b.Property<string>("MsgContent")
                        .HasColumnType("text")
                        .HasColumnName("msg_content");

                    b.Property<MessageType?>("MsgType")
                        .HasColumnType("public.messagetype")
                        .HasColumnName("msg_type");

                    b.Property<string>("PublishGameTime")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("publish_game_time");

                    b.Property<DateTime>("PublishRealTime")
                        .HasColumnType("timestamp(6) without time zone")
                        .HasColumnName("publish_real_time");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Uuid")
                        .HasName("messages_pkey");

                    b.HasIndex("SenderId");

                    b.HasIndex(new[] { "ConferenceId", "IsSecret", "PublishRealTime" }, "idx_messages_conference_public_time")
                        .IsDescending(false, false, true);

                    b.HasIndex(new[] { "ConferenceId", "SenderId" }, "idx_messages_conference_sender");

                    b.HasIndex(new[] { "IsSecret", "PublishRealTime" }, "idx_messages_secret_lookup")
                        .IsDescending(false, true);

                    b.ToTable("messages", null, t =>
                        {
                            t.HasCheckConstraint("chk_messages_brief_not_blank", "brief is null or btrim(brief) <> ''");

                            t.HasCheckConstraint("chk_messages_publish_game_time_not_blank", "btrim(publish_game_time) <> ''");

                            t.HasCheckConstraint("chk_messages_title_not_blank", "title is null or btrim(title) <> ''");
                        });
                });

            modelBuilder.Entity("AsyaMun.Api.Models.MessageReceiver", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("ReadableAt")
                        .HasColumnType("timestamp(6) without time zone")
                        .HasColumnName("readable_at");

                    b.HasKey("MessageId", "UserId")
                        .HasName("message_receivers_pkey");

                    b.HasIndex(new[] { "UserId", "ReadableAt" }, "idx_message_receivers_user_readable");

                    b.ToTable("message_receivers", (string)null);
                });

            modelBuilder.Entity("AsyaMun.Api.Models.Round", b =>
                {
                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<Guid>("ConferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("conference_id");

                    b.Property<long>("DurationSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_seconds");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("timestamp(6) without time zone")
                        .HasColumnName("end_at");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("NextRoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("next_round_id");

                    b.Property<long>("RemainingSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("remaining_seconds");

                    b.Property<RoundStatus>("Status")
                        .HasColumnType("public.roundstatus")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(6) without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Uuid")
                        .HasName("rounds_pkey");

                    b.HasIndex("NextRoundId");

                    b.HasIndex(new[] { "ConferenceId", "IsCurrent" }, "idx_round_conference_current");

                    b.HasIndex(new[] { "ConferenceId", "UpdatedAt" }, "idx_round_conference_updated_at")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "EndAt" }, "idx_round_end_at");

                    b.HasIndex(new[] { "Status", "EndAt" }, "idx_round_expired_current")
                        .HasFilter("is_current");

                    b.HasIndex(new[] { "ConferenceId" }, "uk_rounds_one_current_per_conference")
                        .IsUnique()
                        .HasFilter("is_current");

                    b.ToTable("rounds", null, t =>
                        {
                            t.HasCheckConstraint("chk_rounds_duration_non_negative", "duration_seconds >= 0");

                            t.HasCheckConstraint("chk_rounds_name_not_blank", "btrim(name) <> ''");

                            t.HasCheckConstraint("chk_rounds_next_round_not_self", "next_round_id is null or next_round_id <> uuid");

                            t.HasCheckConstraint("chk_rounds_remaining_non_negative", "remaining_seconds >= 0");

                            t.HasCheckConstraint("chk_rounds_remaining_not_exceed_duration", "remaining_seconds <= duration_seconds");
                        });
                });

            modelBuilder.Entity("AsyaMun.Api.Models.SystemConfig", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("config_value");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.HasKey("ConfigKey")
                        .HasName("system_configs_pkey");

                    b.ToTable("system_configs", null, t =>
                        {
                            t.HasCheckConstraint("chk_system_configs_key_not_blank", "btrim(config_key) <> ''");

                            t.HasCheckConstraint("chk_system_configs_value_not_blank", "btrim(config_value) <> ''");
                        });
                });

            modelBuilder.Entity("AsyaMun.Api.Models.TimeAnchor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AnchorGameTime")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("anchor_game_time");

                    b.Property<DateTime?>("AnchorRealTime")
                        .HasColumnType("timestamp(6) without time zone")
                        .HasColumnName("anchor_real_time");

                    b.Property<Guid>("ConferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("conference_id");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<decimal?>("TimeRatio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("time_ratio");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp(6) without time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("time_anchors_pkey");

                    b.HasIndex(new[] { "ConferenceId", "IsCurrent" }, "idx_time_anchors_conference_current");

                    b.HasIndex(new[] { "ConferenceId", "Id" }, "idx_time_anchors_conference_id")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "ConferenceId" }, "uk_time_anchors_one_current_per_conference")
                        .IsUnique()
                        .HasFilter("is_current");

                    b.ToTable("time_anchors", null, t =>
                        {
                            t.HasCheckConstraint("chk_time_anchors_payload_all_or_none", "(anchor_real_time is null and anchor_game_time is null and time_ratio is null) or (anchor_real_time is not null and anchor_game_time is not null and time_ratio is not null)");

                            t.HasCheckConstraint("chk_time_anchors_ratio_non_negative", "time_ratio is null or time_ratio >= 0");
                        });
                });

            modelBuilder.Entity("AsyaMun.Api.Models.User", b =>
                {
                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<int>("AuthVersion")
                        .HasColumnType("integer")
                        .HasColumnName("auth_version");

                    b.Property<Guid?>("ConferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("conference_id");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<UserRole>("Role")
                        .HasColumnType("public.userrole")
                        .HasColumnName("role");

                    b.HasKey("Uuid")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "ConferenceId" }, "idx_users_conference_id");

                    b.HasIndex(new[] { "Role" }, "idx_users_role");

                    b.HasIndex(new[] { "Name" }, "uk_users_name")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("chk_users_display_name_not_blank", "display_name is null or btrim(display_name) <> ''");

                            t.HasCheckConstraint("chk_users_name_not_blank", "btrim(name) <> ''");

                            t.HasCheckConstraint("chk_users_password_not_blank", "btrim(password) <> ''");
                        });
                });

            modelBuilder.Entity("AsyaMun.Api.Models.UserGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("group_name");

                    b.HasKey("Id")
                        .HasName("user_groups_pkey");

                    b.HasIndex(new[] { "GroupName" }, "uk_user_groups_group_name")
                        .IsUnique();

                    b.ToTable("user_groups", null, t =>
                        {
                            t.HasCheckConstraint("chk_user_groups_group_name_not_blank", "btrim(group_name) <> ''");
                        });
                });

            modelBuilder.Entity("UserGroupMember", b =>
                {
                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.HasKey("GroupId", "UserUuid")
                        .HasName("user_group_members_pkey");

                    b.HasIndex(new[] { "UserUuid" }, "idx_user_group_members_user_uuid");

                    b.ToTable("user_group_members", (string)null);
                });

            modelBuilder.Entity("AsyaMun.Api.Models.Attachment", b =>
                {
                    b.HasOne("AsyaMun.Api.Models.Message", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .HasConstraintName("fk_attachments_message");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("AsyaMun.Api.Models.DelegateAttrConfig", b =>
                {
                    b.HasOne("AsyaMun.Api.Models.Conference", "Conference")
                        .WithMany("DelegateAttrConfigs")
                        .HasForeignKey("ConferenceId")
                        .IsRequired()
                        .HasConstraintName("fk_delegate_attr_configs_conference");

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("AsyaMun.Api.Models.DelegateAttrRecord", b =>
                {
                    b.HasOne("AsyaMun.Api.Models.Conference", "Conference")
                        .WithMany("DelegateAttrRecords")
                        .HasForeignKey("ConferenceId")
                        .IsRequired()
                        .HasConstraintName("fk_delegate_attr_records_conference");

                    b.HasOne("AsyaMun.Api.Models.User", "Delegate")
                        .WithMany("DelegateAttrRecords")
                        .HasForeignKey("DelegateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delegate_attr_records_delegate");

                    b.Navigation("Conference");

                    b.Navigation("Delegate");
                });

            modelBuilder.Entity("AsyaMun.Api.Models.DelegateAttrValue", b =>
                {
                    b.HasOne("AsyaMun.Api.Models.DelegateAttrConfig", "AttrConfig")
                        .WithMany("DelegateAttrValues")
                        .HasForeignKey("AttrConfigId")
                        .IsRequired()
                        .HasConstraintName("fk_delegate_attr_values_attr_config");

                    b.HasOne("AsyaMun.Api.Models.DelegateAttrRecord", "Record")
                        .WithMany("DelegateAttrValues")
                        .HasForeignKey("RecordId")
                        .IsRequired()
                        .HasConstraintName("fk_delegate_attr_values_record");

                    b.Navigation("AttrConfig");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("AsyaMun.Api.Models.Instruction", b =>
                {
                    b.HasOne("AsyaMun.Api.Models.Conference", "Conference")
                        .WithMany("Instructions")
                        .HasForeignKey("ConferenceId")
                        .IsRequired()
                        .HasConstraintName("fk_instructions_conference");

                    b.HasOne("AsyaMun.Api.Models.User", "ReviewedByNavigation")
                        .WithMany("InstructionReviewedByNavigations")
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_instructions_reviewed_by");

                    b.HasOne("AsyaMun.Api.Models.User", "Submitter")
                        .WithMany("InstructionSubmitters")
                        .HasForeignKey("SubmitterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_instructions_submitter");

                    b.Navigation("Conference");

                    b.Navigation("ReviewedByNavigation");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("AsyaMun.Api.Models.Message", b =>
                {
                    b.HasOne("AsyaMun.Api.Models.Conference", "Conference")
                        .WithMany("Messages")
                        .HasForeignKey("ConferenceId")
                        .IsRequired()
                        .HasConstraintName("fk_messages_conference");

                    b.HasOne("AsyaMun.Api.Models.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_messages_sender");

                    b.Navigation("Conference");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("AsyaMun.Api.Models.MessageReceiver", b =>
                {
                    b.HasOne("AsyaMun.Api.Models.Message", "Message")
                        .WithMany("MessageReceivers")
                        .HasForeignKey("MessageId")
                        .IsRequired()
                        .HasConstraintName("fk_message_receivers_message");

                    b.HasOne("AsyaMun.Api.Models.User", "User")
                        .WithMany("MessageReceivers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_receivers_user");

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AsyaMun.Api.Models.Round", b =>
                {
                    b.HasOne("AsyaMun.Api.Models.Conference", "Conference")
                        .WithOne("Round")
                        .HasForeignKey("AsyaMun.Api.Models.Round", "ConferenceId")
                        .IsRequired()
                        .HasConstraintName("fk_rounds_conference");

                    b.HasOne("AsyaMun.Api.Models.Round", "NextRound")
                        .WithMany("InverseNextRound")
                        .HasForeignKey("NextRoundId")
                        .HasConstraintName("fk_rounds_next_round");

                    b.Navigation("Conference");

                    b.Navigation("NextRound");
                });

            modelBuilder.Entity("AsyaMun.Api.Models.TimeAnchor", b =>
                {
                    b.HasOne("AsyaMun.Api.Models.Conference", "Conference")
                        .WithOne("TimeAnchor")
                        .HasForeignKey("AsyaMun.Api.Models.TimeAnchor", "ConferenceId")
                        .IsRequired()
                        .HasConstraintName("fk_time_anchors_conference");

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("AsyaMun.Api.Models.User", b =>
                {
                    b.HasOne("AsyaMun.Api.Models.Conference", "Conference")
                        .WithMany("Users")
                        .HasForeignKey("ConferenceId")
                        .HasConstraintName("fk_users_conference");

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("UserGroupMember", b =>
                {
                    b.HasOne("AsyaMun.Api.Models.UserGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("fk_user_group_members_group");

                    b.HasOne("AsyaMun.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_group_members_user");
                });

            modelBuilder.Entity("AsyaMun.Api.Models.Conference", b =>
                {
                    b.Navigation("DelegateAttrConfigs");

                    b.Navigation("DelegateAttrRecords");

                    b.Navigation("Instructions");

                    b.Navigation("Messages");

                    b.Navigation("Round");

                    b.Navigation("TimeAnchor");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AsyaMun.Api.Models.DelegateAttrConfig", b =>
                {
                    b.Navigation("DelegateAttrValues");
                });

            modelBuilder.Entity("AsyaMun.Api.Models.DelegateAttrRecord", b =>
                {
                    b.Navigation("DelegateAttrValues");
                });

            modelBuilder.Entity("AsyaMun.Api.Models.Message", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("MessageReceivers");
                });

            modelBuilder.Entity("AsyaMun.Api.Models.Round", b =>
                {
                    b.Navigation("InverseNextRound");
                });

            modelBuilder.Entity("AsyaMun.Api.Models.User", b =>
                {
                    b.Navigation("DelegateAttrRecords");

                    b.Navigation("InstructionReviewedByNavigations");

                    b.Navigation("InstructionSubmitters");

                    b.Navigation("MessageReceivers");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
