/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Asya Backend API
 * API documentation for Asya Backend application
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { UploadBody } from "../asyaBackendAPI.schemas";

import { customInstance } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 仅 SYS_ADMIN 可查看，不包含BLOB
 * @summary 列出所有附件
 */
export type listAllResponse200 = {
  data: Blob;
  status: 200;
};

export type listAllResponseSuccess = listAllResponse200 & {
  headers: Headers;
};
export type listAllResponse = listAllResponseSuccess;

export const getListAllUrl = () => {
  return `/api/attachments`;
};

export const listAll = async (
  options?: RequestInit,
): Promise<listAllResponse> => {
  return customInstance<listAllResponse>(getListAllUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListAllQueryKey = () => {
  return [`/api/attachments`] as const;
};

export const getListAllQueryOptions = <
  TData = Awaited<ReturnType<typeof listAll>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listAll>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listAll>>> = ({
    signal,
  }) => listAll({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAll>>
>;
export type ListAllQueryError = unknown;

export function useListAll<
  TData = Awaited<ReturnType<typeof listAll>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAll>>,
          TError,
          Awaited<ReturnType<typeof listAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAll<
  TData = Awaited<ReturnType<typeof listAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAll>>,
          TError,
          Awaited<ReturnType<typeof listAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAll<
  TData = Awaited<ReturnType<typeof listAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 列出所有附件
 */

export function useListAll<
  TData = Awaited<ReturnType<typeof listAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 仅登录用户可上传，单个文件不超过8MB。无需传入targetId。
 * @summary 上传附件
 */
export type uploadResponse200 = {
  data: Blob;
  status: 200;
};

export type uploadResponseSuccess = uploadResponse200 & {
  headers: Headers;
};
export type uploadResponse = uploadResponseSuccess;

export const getUploadUrl = () => {
  return `/api/attachments`;
};

export const upload = async (
  uploadBody: UploadBody,
  options?: RequestInit,
): Promise<uploadResponse> => {
  return customInstance<uploadResponse>(getUploadUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(uploadBody),
  });
};

export const getUploadMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof upload>>,
    TError,
    { data: UploadBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof upload>>,
  TError,
  { data: UploadBody },
  TContext
> => {
  const mutationKey = ["upload"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof upload>>,
    { data: UploadBody }
  > = (props) => {
    const { data } = props ?? {};

    return upload(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UploadMutationResult = NonNullable<
  Awaited<ReturnType<typeof upload>>
>;
export type UploadMutationBody = UploadBody;
export type UploadMutationError = unknown;

/**
 * @summary 上传附件
 */
export const useUpload = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof upload>>,
      TError,
      { data: UploadBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof upload>>,
  TError,
  { data: UploadBody },
  TContext
> => {
  return useMutation(getUploadMutationOptions(options), queryClient);
};
/**
 * 登录用户可查看单个附件信息，不包含BLOB
 * @summary 查询单个附件信息
 */
export type getOne1Response200 = {
  data: Blob;
  status: 200;
};

export type getOne1ResponseSuccess = getOne1Response200 & {
  headers: Headers;
};
export type getOne1Response = getOne1ResponseSuccess;

export const getGetOne1Url = (uuid: string) => {
  return `/api/attachments/${uuid}`;
};

export const getOne1 = async (
  uuid: string,
  options?: RequestInit,
): Promise<getOne1Response> => {
  return customInstance<getOne1Response>(getGetOne1Url(uuid), {
    ...options,
    method: "GET",
  });
};

export const getGetOne1QueryKey = (uuid: string) => {
  return [`/api/attachments/${uuid}`] as const;
};

export const getGetOne1QueryOptions = <
  TData = Awaited<ReturnType<typeof getOne1>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOne1>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOne1QueryKey(uuid);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOne1>>> = ({
    signal,
  }) => getOne1(uuid, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!uuid,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getOne1>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetOne1QueryResult = NonNullable<
  Awaited<ReturnType<typeof getOne1>>
>;
export type GetOne1QueryError = unknown;

export function useGetOne1<
  TData = Awaited<ReturnType<typeof getOne1>>,
  TError = unknown,
>(
  uuid: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOne1>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOne1>>,
          TError,
          Awaited<ReturnType<typeof getOne1>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOne1<
  TData = Awaited<ReturnType<typeof getOne1>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOne1>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOne1>>,
          TError,
          Awaited<ReturnType<typeof getOne1>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOne1<
  TData = Awaited<ReturnType<typeof getOne1>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOne1>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询单个附件信息
 */

export function useGetOne1<
  TData = Awaited<ReturnType<typeof getOne1>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOne1>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOne1QueryOptions(uuid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * DH、DM、SYS_ADMIN 可删除
 * @summary 删除附件
 */
export type delete1Response200 = {
  data: Blob;
  status: 200;
};

export type delete1ResponseSuccess = delete1Response200 & {
  headers: Headers;
};
export type delete1Response = delete1ResponseSuccess;

export const getDelete1Url = (uuid: string) => {
  return `/api/attachments/${uuid}`;
};

export const delete1 = async (
  uuid: string,
  options?: RequestInit,
): Promise<delete1Response> => {
  return customInstance<delete1Response>(getDelete1Url(uuid), {
    ...options,
    method: "DELETE",
  });
};

export const getDelete1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof delete1>>,
    TError,
    { uuid: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof delete1>>,
  TError,
  { uuid: string },
  TContext
> => {
  const mutationKey = ["delete1"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof delete1>>,
    { uuid: string }
  > = (props) => {
    const { uuid } = props ?? {};

    return delete1(uuid, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type Delete1MutationResult = NonNullable<
  Awaited<ReturnType<typeof delete1>>
>;

export type Delete1MutationError = unknown;

/**
 * @summary 删除附件
 */
export const useDelete1 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof delete1>>,
      TError,
      { uuid: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof delete1>>,
  TError,
  { uuid: string },
  TContext
> => {
  return useMutation(getDelete1MutationOptions(options), queryClient);
};
/**
 * 登录用户可下载附件
 * @summary 下载附件
 */
export type downloadResponse200 = {
  data: Blob;
  status: 200;
};

export type downloadResponseSuccess = downloadResponse200 & {
  headers: Headers;
};
export type downloadResponse = downloadResponseSuccess;

export const getDownloadUrl = (uuid: string) => {
  return `/api/attachments/${uuid}/download`;
};

export const download = async (
  uuid: string,
  options?: RequestInit,
): Promise<downloadResponse> => {
  return customInstance<downloadResponse>(getDownloadUrl(uuid), {
    ...options,
    method: "GET",
  });
};

export const getDownloadQueryKey = (uuid: string) => {
  return [`/api/attachments/${uuid}/download`] as const;
};

export const getDownloadQueryOptions = <
  TData = Awaited<ReturnType<typeof download>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof download>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDownloadQueryKey(uuid);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof download>>> = ({
    signal,
  }) => download(uuid, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!uuid,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof download>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type DownloadQueryResult = NonNullable<
  Awaited<ReturnType<typeof download>>
>;
export type DownloadQueryError = unknown;

export function useDownload<
  TData = Awaited<ReturnType<typeof download>>,
  TError = unknown,
>(
  uuid: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof download>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof download>>,
          TError,
          Awaited<ReturnType<typeof download>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDownload<
  TData = Awaited<ReturnType<typeof download>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof download>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof download>>,
          TError,
          Awaited<ReturnType<typeof download>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDownload<
  TData = Awaited<ReturnType<typeof download>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof download>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 下载附件
 */

export function useDownload<
  TData = Awaited<ReturnType<typeof download>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof download>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDownloadQueryOptions(uuid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
