namespace AsyaMun.Api.Models;

public enum ConferenceStatus
{
    PREPARING,
    RUNNING,
    COMPLETED
}

public enum UserRole
{
    DELEGATE,
    DM,
    DH,
    SYS_ADMIN
}

public enum MessageType
{
    EVENT,
    NEWS,
    CRISIS,
    SECRET_LETTER,
    WAR_REPORT,
    MEMORANDUM,
    PROTOCOL,
    AMENDMENT,
    DECLARATION
}

public enum AttachmentTargetType
{
    MESSAGE,
    DIRECTIVE,
    ANNOUNCEMENT
}

public enum AuditActionType
{
    USER_REGISTER,
    USER_LOGIN,
    USER_BATCH_REGISTER,
    USER_UPDATE,
    USER_DELETE,
    USER_PASSWORD_RESET,
    USER_REGISTRATION_SWITCH,
    MESSAGE_CREATE,
    MESSAGE_UPDATE,
    MESSAGE_DELETE,
    ATTACHMENT_UPLOAD,
    ATTACHMENT_DELETE,
    ANNOUNCEMENT_IMAGE_UPDATE,
    CONFERENCE_CREATE,
    CONFERENCE_UPDATE,
    CONFERENCE_ASSIGN_USER,
    USER_GROUP_CREATE,
    USER_GROUP_UPDATE,
    USER_GROUP_DELETE,
    USER_GROUP_MEMBERS_UPDATE,
    USER_GROUP_MEMBER_REMOVE,
    TIMELINE_UPDATE,
    TIMELINE_JUMP,
    ROUND_PUBLISH,
    ROUND_PAUSE,
    ROUND_RESUME,
    ROUND_SET_NEXT,
    ROUND_UPDATE,
    ROUND_SET_CURRENT,
    ROUND_SET_REMAINING,
    ROUND_AUTO_ADVANCE,
    INSTRUCTION_CREATE,
    INSTRUCTION_REVIEW,
    INSTRUCTION_SUBMISSION_SWITCH,
    DELEGATE_ATTR_CONFIG_CREATE,
    DELEGATE_ATTR_CONFIG_UPDATE,
    DELEGATE_ATTR_RECORD_CREATE,
    DELEGATE_ATTR_RECORD_UPDATE,
    DELEGATE_ATTR_RECORD_DELETE,
    TEST_DATA_BOOTSTRAP,
    USER_BATCH_REGISTER_FULL
}

public enum InstructionType
{
    MILITARY,
    DIPLOMACY,
    INTERNAL,
    OTHER,
    ECONOMY
}

public enum InstructionStatus
{
    SUBMITTED,
    IN_PROGRESS,
    REJECTED,
    FEEDBACKED
}

public enum RoundStatus
{
    RUNNING,
    PAUSED
}

public enum DelegateAttrType
{
    TEXT,
    NUMBER
}