package top.bearingwall.asya.model

enum class AuditActionType {
    USER_REGISTER,
    USER_LOGIN,
    USER_BATCH_REGISTER,
    USER_UPDATE,
    USER_DELETE,
    USER_PASSWORD_RESET,
    MESSAGE_CREATE,
    MESSAGE_UPDATE,
    MESSAGE_DELETE,
    CONFERENCE_CREATE,
    CONFERENCE_UPDATE,
    CONFERENCE_ASSIGN_USER,
    TIMELINE_UPDATE,
    TIMELINE_JUMP
}

