/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Asya Backend API
 * API documentation for Asya Backend application
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  SseEmitter,
  TimeJumpRequest,
  TimeUpdateRequest,
} from "../asyaBackendAPI.schemas";

import { customInstance } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 仅 DM、DH、SYS_ADMIN 可操作
 * @summary 启动/恢复/变速时间轴
 */
export type update1Response200 = {
  data: Blob;
  status: 200;
};

export type update1ResponseSuccess = update1Response200 & {
  headers: Headers;
};
export type update1Response = update1ResponseSuccess;

export const getUpdate1Url = () => {
  return `/api/time/update`;
};

export const update1 = async (
  timeUpdateRequest: TimeUpdateRequest,
  options?: RequestInit,
): Promise<update1Response> => {
  return customInstance<update1Response>(getUpdate1Url(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(timeUpdateRequest),
  });
};

export const getUpdate1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof update1>>,
    TError,
    { data: TimeUpdateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof update1>>,
  TError,
  { data: TimeUpdateRequest },
  TContext
> => {
  const mutationKey = ["update1"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof update1>>,
    { data: TimeUpdateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return update1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type Update1MutationResult = NonNullable<
  Awaited<ReturnType<typeof update1>>
>;
export type Update1MutationBody = TimeUpdateRequest;
export type Update1MutationError = unknown;

/**
 * @summary 启动/恢复/变速时间轴
 */
export const useUpdate1 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof update1>>,
      TError,
      { data: TimeUpdateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof update1>>,
  TError,
  { data: TimeUpdateRequest },
  TContext
> => {
  return useMutation(getUpdate1MutationOptions(options), queryClient);
};
/**
 * 用于时间快进/回滚，仅 DM、DH、SYS_ADMIN 可操作
 * @summary 时间跨度跳跃
 */
export type jumpResponse200 = {
  data: Blob;
  status: 200;
};

export type jumpResponseSuccess = jumpResponse200 & {
  headers: Headers;
};
export type jumpResponse = jumpResponseSuccess;

export const getJumpUrl = () => {
  return `/api/time/jump`;
};

export const jump = async (
  timeJumpRequest: TimeJumpRequest,
  options?: RequestInit,
): Promise<jumpResponse> => {
  return customInstance<jumpResponse>(getJumpUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(timeJumpRequest),
  });
};

export const getJumpMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof jump>>,
    TError,
    { data: TimeJumpRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof jump>>,
  TError,
  { data: TimeJumpRequest },
  TContext
> => {
  const mutationKey = ["jump"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof jump>>,
    { data: TimeJumpRequest }
  > = (props) => {
    const { data } = props ?? {};

    return jump(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type JumpMutationResult = NonNullable<Awaited<ReturnType<typeof jump>>>;
export type JumpMutationBody = TimeJumpRequest;
export type JumpMutationError = unknown;

/**
 * @summary 时间跨度跳跃
 */
export const useJump = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof jump>>,
      TError,
      { data: TimeJumpRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof jump>>,
  TError,
  { data: TimeJumpRequest },
  TContext
> => {
  return useMutation(getJumpMutationOptions(options), queryClient);
};
/**
 * DM、DH、SYS_ADMIN 可查看
 * @summary 查看所有时间锚点
 */
export type getAllResponse200 = {
  data: Blob;
  status: 200;
};

export type getAllResponseSuccess = getAllResponse200 & {
  headers: Headers;
};
export type getAllResponse = getAllResponseSuccess;

export const getGetAllUrl = () => {
  return `/api/time`;
};

export const getAll = async (
  options?: RequestInit,
): Promise<getAllResponse> => {
  return customInstance<getAllResponse>(getGetAllUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetAllQueryKey = () => {
  return [`/api/time`] as const;
};

export const getGetAllQueryOptions = <
  TData = Awaited<ReturnType<typeof getAll>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAll>>> = ({
    signal,
  }) => getAll({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllQueryResult = NonNullable<Awaited<ReturnType<typeof getAll>>>;
export type GetAllQueryError = unknown;

export function useGetAll<
  TData = Awaited<ReturnType<typeof getAll>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAll>>,
          TError,
          Awaited<ReturnType<typeof getAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAll<
  TData = Awaited<ReturnType<typeof getAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAll>>,
          TError,
          Awaited<ReturnType<typeof getAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAll<
  TData = Awaited<ReturnType<typeof getAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查看所有时间锚点
 */

export function useGetAll<
  TData = Awaited<ReturnType<typeof getAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * SSE流
 * @summary 订阅时间轴变化
 */
export type streamResponse200 = {
  data: SseEmitter;
  status: 200;
};

export type streamResponseSuccess = streamResponse200 & {
  headers: Headers;
};
export type streamResponse = streamResponseSuccess;

export const getStreamUrl = () => {
  return `/api/time/stream`;
};

export const stream = async (
  options?: RequestInit,
): Promise<streamResponse> => {
  return customInstance<streamResponse>(getStreamUrl(), {
    ...options,
    method: "GET",
  });
};

export const getStreamQueryKey = () => {
  return [`/api/time/stream`] as const;
};

export const getStreamQueryOptions = <
  TData = Awaited<ReturnType<typeof stream>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof stream>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getStreamQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof stream>>> = ({
    signal,
  }) => stream({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof stream>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StreamQueryResult = NonNullable<Awaited<ReturnType<typeof stream>>>;
export type StreamQueryError = unknown;

export function useStream<
  TData = Awaited<ReturnType<typeof stream>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof stream>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof stream>>,
          TError,
          Awaited<ReturnType<typeof stream>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStream<
  TData = Awaited<ReturnType<typeof stream>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof stream>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof stream>>,
          TError,
          Awaited<ReturnType<typeof stream>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStream<
  TData = Awaited<ReturnType<typeof stream>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof stream>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 订阅时间轴变化
 */

export function useStream<
  TData = Awaited<ReturnType<typeof stream>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof stream>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getStreamQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 所有登录用户可查看
 * @summary 查看最新时间锚点
 */
export type getLatestResponse200 = {
  data: Blob;
  status: 200;
};

export type getLatestResponseSuccess = getLatestResponse200 & {
  headers: Headers;
};
export type getLatestResponse = getLatestResponseSuccess;

export const getGetLatestUrl = () => {
  return `/api/time/latest`;
};

export const getLatest = async (
  options?: RequestInit,
): Promise<getLatestResponse> => {
  return customInstance<getLatestResponse>(getGetLatestUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetLatestQueryKey = () => {
  return [`/api/time/latest`] as const;
};

export const getGetLatestQueryOptions = <
  TData = Awaited<ReturnType<typeof getLatest>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getLatest>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLatestQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLatest>>> = ({
    signal,
  }) => getLatest({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLatest>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLatestQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLatest>>
>;
export type GetLatestQueryError = unknown;

export function useGetLatest<
  TData = Awaited<ReturnType<typeof getLatest>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLatest>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLatest>>,
          TError,
          Awaited<ReturnType<typeof getLatest>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLatest<
  TData = Awaited<ReturnType<typeof getLatest>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLatest>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLatest>>,
          TError,
          Awaited<ReturnType<typeof getLatest>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLatest<
  TData = Awaited<ReturnType<typeof getLatest>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLatest>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查看最新时间锚点
 */

export function useGetLatest<
  TData = Awaited<ReturnType<typeof getLatest>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLatest>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetLatestQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 基于最新锚点计算的实时游戏时间
 * @summary 查询当前游戏时间
 */
export type getCurrentResponse200 = {
  data: Blob;
  status: 200;
};

export type getCurrentResponseSuccess = getCurrentResponse200 & {
  headers: Headers;
};
export type getCurrentResponse = getCurrentResponseSuccess;

export const getGetCurrentUrl = () => {
  return `/api/time/current`;
};

export const getCurrent = async (
  options?: RequestInit,
): Promise<getCurrentResponse> => {
  return customInstance<getCurrentResponse>(getGetCurrentUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetCurrentQueryKey = () => {
  return [`/api/time/current`] as const;
};

export const getGetCurrentQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrent>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getCurrent>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrentQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrent>>> = ({
    signal,
  }) => getCurrent({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrent>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCurrentQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrent>>
>;
export type GetCurrentQueryError = unknown;

export function useGetCurrent<
  TData = Awaited<ReturnType<typeof getCurrent>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrent>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrent>>,
          TError,
          Awaited<ReturnType<typeof getCurrent>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCurrent<
  TData = Awaited<ReturnType<typeof getCurrent>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrent>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrent>>,
          TError,
          Awaited<ReturnType<typeof getCurrent>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCurrent<
  TData = Awaited<ReturnType<typeof getCurrent>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrent>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询当前游戏时间
 */

export function useGetCurrent<
  TData = Awaited<ReturnType<typeof getCurrent>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrent>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCurrentQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
