/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Asya Backend API
 * API documentation for Asya Backend application
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetForManagementParams,
  GetMyInstructionsParams,
  InstructionCreateRequest,
  InstructionReviewRequest,
  SetSubmissionSwitchParams,
} from "../asyaBackendAPI.schemas";

import { customInstance } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const appendQueryParam = (
  normalizedParams: URLSearchParams,
  key: string,
  value: unknown,
) => {
  if (value === undefined || value === null) return;
  if (typeof value === "string" && value.trim() === "") return;
  normalizedParams.append(key, String(value));
};

const buildQueryString = (params?: Record<string, unknown>) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value === undefined || value === null) return;

    if (key === "pageable" && typeof value === "object" && !Array.isArray(value)) {
      const pageable = value as {
        page?: number;
        size?: number;
        sort?: string[];
      };
      appendQueryParam(normalizedParams, "page", pageable.page);
      appendQueryParam(normalizedParams, "size", pageable.size);
      if (Array.isArray(pageable.sort)) {
        pageable.sort.forEach((sort) =>
          appendQueryParam(normalizedParams, "sort", sort),
        );
      }
      return;
    }

    if (Array.isArray(value)) {
      value.forEach((item) => appendQueryParam(normalizedParams, key, item));
      return;
    }

    appendQueryParam(normalizedParams, key, value);
  });

  return normalizedParams.toString();
};

/**
 * 仅代表可提交，提交后不可修改
 * @summary 提交指令
 */
export type create2Response200 = {
  data: Blob;
  status: 200;
};

export type create2ResponseSuccess = create2Response200 & {
  headers: Headers;
};
export type create2Response = create2ResponseSuccess;

export const getCreate2Url = () => {
  return `/api/instructions`;
};

export const create2 = async (
  instructionCreateRequest: InstructionCreateRequest,
  options?: RequestInit,
): Promise<create2Response> => {
  return customInstance<create2Response>(getCreate2Url(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(instructionCreateRequest),
  });
};

export const getCreate2MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof create2>>,
    TError,
    { data: InstructionCreateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof create2>>,
  TError,
  { data: InstructionCreateRequest },
  TContext
> => {
  const mutationKey = ["create2"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof create2>>,
    { data: InstructionCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return create2(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type Create2MutationResult = NonNullable<
  Awaited<ReturnType<typeof create2>>
>;
export type Create2MutationBody = InstructionCreateRequest;
export type Create2MutationError = unknown;

/**
 * @summary 提交指令
 */
export const useCreate2 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof create2>>,
      TError,
      { data: InstructionCreateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof create2>>,
  TError,
  { data: InstructionCreateRequest },
  TContext
> => {
  return useMutation(getCreate2MutationOptions(options), queryClient);
};
/**
 * DH/DM/SYS_ADMIN 可更新状态并写入当前批阅评语
 * @summary 批改指令
 */
export type reviewResponse200 = {
  data: Blob;
  status: 200;
};

export type reviewResponseSuccess = reviewResponse200 & {
  headers: Headers;
};
export type reviewResponse = reviewResponseSuccess;

export const getReviewUrl = (uuid: string) => {
  return `/api/instructions/${uuid}/review`;
};

export const review = async (
  uuid: string,
  instructionReviewRequest: InstructionReviewRequest,
  options?: RequestInit,
): Promise<reviewResponse> => {
  return customInstance<reviewResponse>(getReviewUrl(uuid), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(instructionReviewRequest),
  });
};

export const getReviewMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof review>>,
    TError,
    { uuid: string; data: InstructionReviewRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof review>>,
  TError,
  { uuid: string; data: InstructionReviewRequest },
  TContext
> => {
  const mutationKey = ["review"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof review>>,
    { uuid: string; data: InstructionReviewRequest }
  > = (props) => {
    const { uuid, data } = props ?? {};

    return review(uuid, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ReviewMutationResult = NonNullable<
  Awaited<ReturnType<typeof review>>
>;
export type ReviewMutationBody = InstructionReviewRequest;
export type ReviewMutationError = unknown;

/**
 * @summary 批改指令
 */
export const useReview = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof review>>,
      TError,
      { uuid: string; data: InstructionReviewRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof review>>,
  TError,
  { uuid: string; data: InstructionReviewRequest },
  TContext
> => {
  return useMutation(getReviewMutationOptions(options), queryClient);
};
/**
 * @summary 查询全局指令提交暂停开关
 */
export type getSubmissionSwitchResponse200 = {
  data: Blob;
  status: 200;
};

export type getSubmissionSwitchResponseSuccess =
  getSubmissionSwitchResponse200 & {
    headers: Headers;
  };
export type getSubmissionSwitchResponse = getSubmissionSwitchResponseSuccess;

export const getGetSubmissionSwitchUrl = () => {
  return `/api/instructions/submission-switch`;
};

export const getSubmissionSwitch = async (
  options?: RequestInit,
): Promise<getSubmissionSwitchResponse> => {
  return customInstance<getSubmissionSwitchResponse>(
    getGetSubmissionSwitchUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetSubmissionSwitchQueryKey = () => {
  return [`/api/instructions/submission-switch`] as const;
};

export const getGetSubmissionSwitchQueryOptions = <
  TData = Awaited<ReturnType<typeof getSubmissionSwitch>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getSubmissionSwitch>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSubmissionSwitchQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSubmissionSwitch>>
  > = ({ signal }) => getSubmissionSwitch({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSubmissionSwitch>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSubmissionSwitchQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSubmissionSwitch>>
>;
export type GetSubmissionSwitchQueryError = unknown;

export function useGetSubmissionSwitch<
  TData = Awaited<ReturnType<typeof getSubmissionSwitch>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSubmissionSwitch>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubmissionSwitch>>,
          TError,
          Awaited<ReturnType<typeof getSubmissionSwitch>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSubmissionSwitch<
  TData = Awaited<ReturnType<typeof getSubmissionSwitch>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSubmissionSwitch>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubmissionSwitch>>,
          TError,
          Awaited<ReturnType<typeof getSubmissionSwitch>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSubmissionSwitch<
  TData = Awaited<ReturnType<typeof getSubmissionSwitch>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSubmissionSwitch>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询全局指令提交暂停开关
 */

export function useGetSubmissionSwitch<
  TData = Awaited<ReturnType<typeof getSubmissionSwitch>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSubmissionSwitch>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetSubmissionSwitchQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 仅 SYS_ADMIN 可设置。paused=true 表示暂停提交
 * @summary 设置全局指令提交暂停开关
 */
export type setSubmissionSwitchResponse200 = {
  data: Blob;
  status: 200;
};

export type setSubmissionSwitchResponseSuccess =
  setSubmissionSwitchResponse200 & {
    headers: Headers;
  };
export type setSubmissionSwitchResponse = setSubmissionSwitchResponseSuccess;

export const getSetSubmissionSwitchUrl = (
  params: SetSubmissionSwitchParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/instructions/submission-switch?${stringifiedParams}`
    : `/api/instructions/submission-switch`;
};

export const setSubmissionSwitch = async (
  params: SetSubmissionSwitchParams,
  options?: RequestInit,
): Promise<setSubmissionSwitchResponse> => {
  return customInstance<setSubmissionSwitchResponse>(
    getSetSubmissionSwitchUrl(params),
    {
      ...options,
      method: "POST",
    },
  );
};

export const getSetSubmissionSwitchMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof setSubmissionSwitch>>,
    TError,
    { params: SetSubmissionSwitchParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof setSubmissionSwitch>>,
  TError,
  { params: SetSubmissionSwitchParams },
  TContext
> => {
  const mutationKey = ["setSubmissionSwitch"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof setSubmissionSwitch>>,
    { params: SetSubmissionSwitchParams }
  > = (props) => {
    const { params } = props ?? {};

    return setSubmissionSwitch(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SetSubmissionSwitchMutationResult = NonNullable<
  Awaited<ReturnType<typeof setSubmissionSwitch>>
>;

export type SetSubmissionSwitchMutationError = unknown;

/**
 * @summary 设置全局指令提交暂停开关
 */
export const useSetSubmissionSwitch = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof setSubmissionSwitch>>,
      TError,
      { params: SetSubmissionSwitchParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof setSubmissionSwitch>>,
  TError,
  { params: SetSubmissionSwitchParams },
  TContext
> => {
  return useMutation(
    getSetSubmissionSwitchMutationOptions(options),
    queryClient,
  );
};
/**
 * 代表仅可查看自己的，DH/DM/SYS_ADMIN 可查看当前会议全部
 * @summary 查询指令详情
 */
export type getInstructionResponse200 = {
  data: Blob;
  status: 200;
};

export type getInstructionResponseSuccess = getInstructionResponse200 & {
  headers: Headers;
};
export type getInstructionResponse = getInstructionResponseSuccess;

export const getGetInstructionUrl = (uuid: string) => {
  return `/api/instructions/${uuid}`;
};

export const getInstruction = async (
  uuid: string,
  options?: RequestInit,
): Promise<getInstructionResponse> => {
  return customInstance<getInstructionResponse>(getGetInstructionUrl(uuid), {
    ...options,
    method: "GET",
  });
};

export const getGetInstructionQueryKey = (uuid: string) => {
  return [`/api/instructions/${uuid}`] as const;
};

export const getGetInstructionQueryOptions = <
  TData = Awaited<ReturnType<typeof getInstruction>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getInstruction>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetInstructionQueryKey(uuid);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getInstruction>>> = ({
    signal,
  }) => getInstruction(uuid, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!uuid,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getInstruction>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetInstructionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getInstruction>>
>;
export type GetInstructionQueryError = unknown;

export function useGetInstruction<
  TData = Awaited<ReturnType<typeof getInstruction>>,
  TError = unknown,
>(
  uuid: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getInstruction>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInstruction>>,
          TError,
          Awaited<ReturnType<typeof getInstruction>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetInstruction<
  TData = Awaited<ReturnType<typeof getInstruction>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getInstruction>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInstruction>>,
          TError,
          Awaited<ReturnType<typeof getInstruction>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetInstruction<
  TData = Awaited<ReturnType<typeof getInstruction>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getInstruction>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询指令详情
 */

export function useGetInstruction<
  TData = Awaited<ReturnType<typeof getInstruction>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getInstruction>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetInstructionQueryOptions(uuid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 代表分页查询自己提交的指令
 * @summary 查询我的指令
 */
export type getMyInstructionsResponse200 = {
  data: Blob;
  status: 200;
};

export type getMyInstructionsResponseSuccess = getMyInstructionsResponse200 & {
  headers: Headers;
};
export type getMyInstructionsResponse = getMyInstructionsResponseSuccess;

export const getGetMyInstructionsUrl = (params: GetMyInstructionsParams) => {
  const stringifiedParams = buildQueryString(params as Record<string, unknown>);

  return stringifiedParams.length > 0
    ? `/api/instructions/my?${stringifiedParams}`
    : `/api/instructions/my`;
};

export const getMyInstructions = async (
  params: GetMyInstructionsParams,
  options?: RequestInit,
): Promise<getMyInstructionsResponse> => {
  return customInstance<getMyInstructionsResponse>(
    getGetMyInstructionsUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetMyInstructionsQueryKey = (
  params?: GetMyInstructionsParams,
) => {
  return [`/api/instructions/my`, ...(params ? [params] : [])] as const;
};

export const getGetMyInstructionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyInstructions>>,
  TError = unknown,
>(
  params: GetMyInstructionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyInstructions>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMyInstructionsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMyInstructions>>
  > = ({ signal }) => getMyInstructions(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyInstructions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyInstructionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyInstructions>>
>;
export type GetMyInstructionsQueryError = unknown;

export function useGetMyInstructions<
  TData = Awaited<ReturnType<typeof getMyInstructions>>,
  TError = unknown,
>(
  params: GetMyInstructionsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyInstructions>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInstructions>>,
          TError,
          Awaited<ReturnType<typeof getMyInstructions>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyInstructions<
  TData = Awaited<ReturnType<typeof getMyInstructions>>,
  TError = unknown,
>(
  params: GetMyInstructionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyInstructions>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInstructions>>,
          TError,
          Awaited<ReturnType<typeof getMyInstructions>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyInstructions<
  TData = Awaited<ReturnType<typeof getMyInstructions>>,
  TError = unknown,
>(
  params: GetMyInstructionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyInstructions>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询我的指令
 */

export function useGetMyInstructions<
  TData = Awaited<ReturnType<typeof getMyInstructions>>,
  TError = unknown,
>(
  params: GetMyInstructionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyInstructions>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMyInstructionsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * DH/DM/SYS_ADMIN 可按状态、类型、用户组、代表多选筛选当前会议的指令
 * @summary 管理端分页查询指令
 */
export type getForManagementResponse200 = {
  data: Blob;
  status: 200;
};

export type getForManagementResponseSuccess = getForManagementResponse200 & {
  headers: Headers;
};
export type getForManagementResponse = getForManagementResponseSuccess;

export const getGetForManagementUrl = (params: GetForManagementParams) => {
  const stringifiedParams = buildQueryString(params as Record<string, unknown>);

  return stringifiedParams.length > 0
    ? `/api/instructions/manage?${stringifiedParams}`
    : `/api/instructions/manage`;
};

export const getForManagement = async (
  params: GetForManagementParams,
  options?: RequestInit,
): Promise<getForManagementResponse> => {
  return customInstance<getForManagementResponse>(
    getGetForManagementUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetForManagementQueryKey = (
  params?: GetForManagementParams,
) => {
  return [`/api/instructions/manage`, ...(params ? [params] : [])] as const;
};

export const getGetForManagementQueryOptions = <
  TData = Awaited<ReturnType<typeof getForManagement>>,
  TError = unknown,
>(
  params: GetForManagementParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getForManagement>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetForManagementQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getForManagement>>
  > = ({ signal }) => getForManagement(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getForManagement>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetForManagementQueryResult = NonNullable<
  Awaited<ReturnType<typeof getForManagement>>
>;
export type GetForManagementQueryError = unknown;

export function useGetForManagement<
  TData = Awaited<ReturnType<typeof getForManagement>>,
  TError = unknown,
>(
  params: GetForManagementParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getForManagement>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getForManagement>>,
          TError,
          Awaited<ReturnType<typeof getForManagement>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetForManagement<
  TData = Awaited<ReturnType<typeof getForManagement>>,
  TError = unknown,
>(
  params: GetForManagementParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getForManagement>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getForManagement>>,
          TError,
          Awaited<ReturnType<typeof getForManagement>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetForManagement<
  TData = Awaited<ReturnType<typeof getForManagement>>,
  TError = unknown,
>(
  params: GetForManagementParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getForManagement>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 管理端分页查询指令
 */

export function useGetForManagement<
  TData = Awaited<ReturnType<typeof getForManagement>>,
  TError = unknown,
>(
  params: GetForManagementParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getForManagement>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetForManagementQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
