/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Asya Backend API
 * API documentation for Asya Backend application
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { UpdateAnnouncementImageBody } from "../asyaBackendAPI.schemas";

import { customInstance } from "../../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 所有登录用户可查看。未设置时 data 为 null。
 * @summary 查询当前公告图片信息
 */
export type getAnnouncementImageInfoResponse200 = {
  data: Blob;
  status: 200;
};

export type getAnnouncementImageInfoResponseSuccess =
  getAnnouncementImageInfoResponse200 & {
    headers: Headers;
  };
export type getAnnouncementImageInfoResponse =
  getAnnouncementImageInfoResponseSuccess;

export const getGetAnnouncementImageInfoUrl = () => {
  return `/api/announcement/image`;
};

export const getAnnouncementImageInfo = async (
  options?: RequestInit,
): Promise<getAnnouncementImageInfoResponse> => {
  return customInstance<getAnnouncementImageInfoResponse>(
    getGetAnnouncementImageInfoUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetAnnouncementImageInfoQueryKey = () => {
  return [`/api/announcement/image`] as const;
};

export const getGetAnnouncementImageInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof getAnnouncementImageInfo>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAnnouncementImageInfo>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAnnouncementImageInfoQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAnnouncementImageInfo>>
  > = ({ signal }) => getAnnouncementImageInfo({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAnnouncementImageInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAnnouncementImageInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAnnouncementImageInfo>>
>;
export type GetAnnouncementImageInfoQueryError = unknown;

export function useGetAnnouncementImageInfo<
  TData = Awaited<ReturnType<typeof getAnnouncementImageInfo>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAnnouncementImageInfo>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnnouncementImageInfo>>,
          TError,
          Awaited<ReturnType<typeof getAnnouncementImageInfo>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAnnouncementImageInfo<
  TData = Awaited<ReturnType<typeof getAnnouncementImageInfo>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAnnouncementImageInfo>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnnouncementImageInfo>>,
          TError,
          Awaited<ReturnType<typeof getAnnouncementImageInfo>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAnnouncementImageInfo<
  TData = Awaited<ReturnType<typeof getAnnouncementImageInfo>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAnnouncementImageInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询当前公告图片信息
 */

export function useGetAnnouncementImageInfo<
  TData = Awaited<ReturnType<typeof getAnnouncementImageInfo>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAnnouncementImageInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAnnouncementImageInfoQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 仅 SYS_ADMIN、DH、DM 可更新公告图片，更新后自动替换旧图。
 * @summary 更新公告图片
 */
export type updateAnnouncementImageResponse200 = {
  data: Blob;
  status: 200;
};

export type updateAnnouncementImageResponseSuccess =
  updateAnnouncementImageResponse200 & {
    headers: Headers;
  };
export type updateAnnouncementImageResponse =
  updateAnnouncementImageResponseSuccess;

export const getUpdateAnnouncementImageUrl = () => {
  return `/api/announcement/image`;
};

export const updateAnnouncementImage = async (
  updateAnnouncementImageBody: UpdateAnnouncementImageBody,
  options?: RequestInit,
): Promise<updateAnnouncementImageResponse> => {
  return customInstance<updateAnnouncementImageResponse>(
    getUpdateAnnouncementImageUrl(),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateAnnouncementImageBody),
    },
  );
};

export const getUpdateAnnouncementImageMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAnnouncementImage>>,
    TError,
    { data: UpdateAnnouncementImageBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateAnnouncementImage>>,
  TError,
  { data: UpdateAnnouncementImageBody },
  TContext
> => {
  const mutationKey = ["updateAnnouncementImage"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateAnnouncementImage>>,
    { data: UpdateAnnouncementImageBody }
  > = (props) => {
    const { data } = props ?? {};

    return updateAnnouncementImage(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateAnnouncementImageMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAnnouncementImage>>
>;
export type UpdateAnnouncementImageMutationBody = UpdateAnnouncementImageBody;
export type UpdateAnnouncementImageMutationError = unknown;

/**
 * @summary 更新公告图片
 */
export const useUpdateAnnouncementImage = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateAnnouncementImage>>,
      TError,
      { data: UpdateAnnouncementImageBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateAnnouncementImage>>,
  TError,
  { data: UpdateAnnouncementImageBody },
  TContext
> => {
  return useMutation(
    getUpdateAnnouncementImageMutationOptions(options),
    queryClient,
  );
};
/**
 * 所有登录用户可下载当前公告图片。
 * @summary 下载当前公告图片
 */
export type downloadAnnouncementImageResponse200 = {
  data: Blob;
  status: 200;
};

export type downloadAnnouncementImageResponseSuccess =
  downloadAnnouncementImageResponse200 & {
    headers: Headers;
  };
export type downloadAnnouncementImageResponse =
  downloadAnnouncementImageResponseSuccess;

export const getDownloadAnnouncementImageUrl = () => {
  return `/api/announcement/image/download`;
};

export const downloadAnnouncementImage = async (
  options?: RequestInit,
): Promise<downloadAnnouncementImageResponse> => {
  return customInstance<downloadAnnouncementImageResponse>(
    getDownloadAnnouncementImageUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getDownloadAnnouncementImageQueryKey = () => {
  return [`/api/announcement/image/download`] as const;
};

export const getDownloadAnnouncementImageQueryOptions = <
  TData = Awaited<ReturnType<typeof downloadAnnouncementImage>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof downloadAnnouncementImage>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getDownloadAnnouncementImageQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof downloadAnnouncementImage>>
  > = ({ signal }) => downloadAnnouncementImage({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof downloadAnnouncementImage>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DownloadAnnouncementImageQueryResult = NonNullable<
  Awaited<ReturnType<typeof downloadAnnouncementImage>>
>;
export type DownloadAnnouncementImageQueryError = unknown;

export function useDownloadAnnouncementImage<
  TData = Awaited<ReturnType<typeof downloadAnnouncementImage>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof downloadAnnouncementImage>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadAnnouncementImage>>,
          TError,
          Awaited<ReturnType<typeof downloadAnnouncementImage>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDownloadAnnouncementImage<
  TData = Awaited<ReturnType<typeof downloadAnnouncementImage>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof downloadAnnouncementImage>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadAnnouncementImage>>,
          TError,
          Awaited<ReturnType<typeof downloadAnnouncementImage>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDownloadAnnouncementImage<
  TData = Awaited<ReturnType<typeof downloadAnnouncementImage>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof downloadAnnouncementImage>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 下载当前公告图片
 */

export function useDownloadAnnouncementImage<
  TData = Awaited<ReturnType<typeof downloadAnnouncementImage>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof downloadAnnouncementImage>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDownloadAnnouncementImageQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
