package top.bearingwall.asya

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

// Generated by https://start.springboot.io
@SpringBootApplication
class Application

fun main(args: Array<String>) {
    runApplication<Application>(*args)
}