package top.bearingwall.asya

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

// Generated by https://start.springboot.io
@SpringBootApplication
class DemoApplication

fun main(args: Array<String>) {
    runApplication<DemoApplication>(*args)
}